### ISSUE TITLE
[TOTK] Some objects render in and out for one frame on close approach

### ISSUE THREAD

**Issue by ilyabru** [yuzu-emu/yuzu#10539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1453

### Description of Issue

When approaching an object such as a sign post or sign board (both are targetable readable objects in-game), the sign pops in and out for one frame. I've attached a video of this happening. 

https://github.com/yuzu-emu/yuzu/assets/16808230/a0333a19-711a-4470-8973-b76266e01cf4

### Expected Behavior

Sign should retain it's shape at all times at this distance.

### Reproduction Steps

Find a sign post or sign board at any location, the move away and towards it.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11620065/yuzu_log.txt.old.txt)

### System Configuration

CPU: i7-12700K
GPU/Driver: RTX 4090 / 532.03
RAM: 32GB
OS: Windows 11 22H2

**Comment by Squall-Leonhart** [comment]
believe this is fixed in EA already?

**Comment by ilyabru** [comment]
I just tried with EA 3627, the issue is happening there as well.

**Comment by Sincasios** [comment]
No, it is not fixed.

I supose that you think that this fixed the issue: https://github.com/yuzu-emu/yuzu/pull/10418

But not, it was still flikering: https://github.com/yuzu-emu/yuzu/issues/10226#issuecomment-1562373723
