### ISSUE TITLE
Tears of the kingdom crash on launch when using Vulkan 

### ISSUE THREAD

**Issue by StillWRD** [yuzu-emu/yuzu#10581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1453 / EA 3589 - 3601 - 3602 - 3623 - 3630

### Description of Issue

Vulkan crash on launch with recent Nvidia drivers. downgrading to versions from this range 512.XX to 497.XX fixes the issue but introduces other problems.

### Expected Behavior

Game launches using Vulkan with recent Nvidia drivers without the need to downgrade.

### Reproduction Steps

Launch the game using Vulkan with a GTX 970 and driver version 532.03

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11639026/yuzu_log.txt)

### System Configuration

CPU: i5-3330
GPU/Driver: GTX 970 - Driver Version: 532.03
RAM: 8 GB DDR3
OS: Windows 10

**Comment by Squall-Leonhart** [comment]
latest are 535.98, and you can mitigate this by using texture recompression.

**Comment by StillWRD** [comment]
> latest are 535.98, and you can mitigate this by using texture recompression.
> 
> You are severely lacking in system memory though.

I updated to 535.98 and tried ASTC recompression: BC1, BC3, and Uncompressed. Same results. 

Do you think this is a RAM issue? It launches on older drivers though like I mentioned.

**Comment by ferilagi** [comment]
**System Configuration**

CPU: i5-3550
GPU/Driver: GT 630 - Driver Version: 474.30
RAM: 16 GB DDR3, PageFile 32GB
OS: Windows 10

even this card is unsuported with vulkan 1.3 and lack of support,
TOTK work Fine in my system (30fps average) with build 3631 BC1 recompression other than this #10320 issue

**Comment by Maxuru** [comment]
Got the exact same Problem With a GTX970 but 16 Gb DDR4 Ram on The Newer Drivers.

So Ram is probably atleast for me not the Problem.

**Comment by Clemy-beep** [comment]
Same problem here with NVIDIA GeForce RTX3070  and 16 GB DDR4 RAM. Found out a procedure to get it to work but it's bothersome : 

- stop yuzu
- delete tas, dump and shader folders from yuzu folder
- reboot computer
- stop parsec if launched
- quickly (and i mean it) launch game on yuzu
And TADA it works ! But as i said, it's a pain to do that every time i want to play the game

**Comment by mbrickner** [comment]
> Same problem here with NVIDIA GeForce RTX3070 Laptop and 16 GB DDR4 RAM. Found out a procedure to get it to work but it's bothersome :
> 
> * stop yuzu
> * delete tas, dump and shader folders from yuzu folder
> * reboot computer
> * stop parsec if launched
> * quickly (and i mean it) launch game on yuzu
>   And TADA it works ! But as i said, it's a pain to do that every time i want to play the game

I had updated nvidia drivers and was now crashing on launch.  What worked for me based on your suggestion was deleting the sahders folder.
However, the original problem I updated nvidia drivers to try and fix is not addressed. Yuzu crashing and causing a black screen and system unresponsive.  I have to hard reboot by turning off PSU power.  Does not happen in any other situations.

**Comment by EitanGITHUB** [comment]
I have fixed the problem by reverting to the 512.95 driver, maybe try that?

**Comment by mbrickner** [comment]
I ended up still having the issue after updating Nvidia drivers and deleting the shaders folder.

I must have had some bad mods... downloaded the "Lazy pack" and am using 60fps 1080p and it seems to be OK now.

**Comment by blayz45** [comment]
I have the same problem but I don't know where it comes from . I have a 32 GB DDR4 RAM and GPU:Nvidia quadro M1000M (2 GB) Can someone please answer me
