### ISSUE TITLE
Some game crashes on startup when using Firmware

### ISSUE THREAD

**Issue by StefanLenz1** [yuzu-emu/yuzu#10817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline-0-1471 (32fd99cf)  (but happens since a week)

### Description of Issue

After Yuzu worked correctly for a while, both Mario Kart 8 Deluxe and Super Mario Odyssey crash at "loading" after the shaders are loaded with and without DLCs/Updates if any Firmware is installed (tested with Firmware 16.0.1-16.0.3). Super Mario Party works none the less. Both games start when Yuzu has no Firmware installed. 

### Expected Behavior

Games launch without crashing

### Reproduction Steps

flatpak run org.yuzu_emu.yuzu:

Gtk-Message: 17:38:04.835: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:38:04.835: Failed to load module "pk-gtk-module"
Gtk-Message: 17:38:04.836: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:38:04.836: Failed to load module "pk-gtk-module"
qt.qpa.qgnomeplatform: Could not find color scheme  ""

start mario kart 8 deluxe:

Qt: Session management error: None of the authentication protocols specified are supported
libpng warning: iCCP: known incorrect sRGB profile
/usr/include/c++/12.2.0/array:208: constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) [with _Tp = char; long unsigned int _Nm = 8; reference = char&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
/app/bin/yuzu-launcher: line 25:    13 Aborted                 (core dumped) prlimit --nofile=8192 yuzu "$@"

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11779410/yuzu_log.txt)

### System Configuration

CPU: Info: quad core model: AMD Ryzen 5 2400G with Radeon Vega Graphics bits: 64 type: MT MCP arch: Zen rev: 0 cache: L1: 384 KiB L2: 2 MiB L3: 4 MiB

GPU/Driver: Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] vendor: Micro-Star MSI driver: amdgpu v: kernel arch: GCN-4 bus-ID: 10:00.0 temp: 54.0 C
  Display: wayland server: X.Org v: 22.1.9 with: Xwayland v: 22.1.9
    compositor: gnome-shell driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,vesa dri: radeonsi gpu: amdgpu resolution:
    1: 1680x1050  60Hz 2: 1920x1080 60Hz
  API: OpenGL v: 4.6 Mesa 23.1.1 renderer: AMD Radeon RX 570 Series
    (polaris10 LLVM 16.0.4 DRM 3.52 6.3.6-200.fc38.x86_64) direct-render: Yes

RAM: Memory: available: 15.54 GiB used: 4.29 GiB (27.6%)

OS: Kernel: 6.3.6-200.fc38.x86_64 arch: x86_64 bits: 64
    compiler: gcc v: 2.39-9.fc38 Desktop: GNOME v: 44.2 Distro: Fedora release
    38 (Thirty Eight)

**Comment by liamwhite** [comment]
likely fixed by #10797

**Comment by StefanLenz1** [comment]
> likely fixed by #10797

fixed by switching to appimage, so it very likely is the flatpak issue. thank you

**Comment by lat9nq** [comment]
AFIAK if you have system firmware installed, the Flatpak should still work. The fixes in #10797 are mostly focused on installations lacking the firmware, so I will need to test this.

**Comment by lat9nq** [comment]
This should be fixed by #10797 now.

**Comment by StefanLenz1** [comment]
> AFIAK if you have system firmware installed, the Flatpak should still work. The fixes in #10797 are mostly focused on installations lacking the firmware, so I will need to test this.

Then there seems to be another problem with the flatpak version because the appImage one works both with and without firmware

**Comment by StefanLenz1** [comment]
@FearlessTobi I have updated it to the newest flatpak version and I still have the same problem. Seems like it was not the patch lat9nq talked about

**Comment by lat9nq** [comment]
What time zone are you using? The output from running the command `date +"%Z"` would be most helpful.

**Comment by StefanLenz1** [comment]
> What time zone are you using? The output from running the command `date +"%Z"` would be most helpful.
> 
> I am otherwise unable to reproduce this issue.

@lat9nq 
Linux: CEST,
yuzu: CET

And you seem to have found the issue. Switching to "Region: USA", Time Zone: "Auto" fixes the issue. Going back to "Region: Europe", "Time Zone: CET" leads to crashes again. Now running "yuzu-mainline.git to mainline-0-1474 (8cea3138)"

**Comment by lat9nq** [comment]
Found the actual issue. Nintendo made another change to the time zone implementation that we weren't accounting for.

The reason time zone Auto works and not CET is that Auto just selects one of the pure GMT time zone offsets (assuming the compiler lacks support for C++20 tzdb, which is all of them except Microsoft's MSVC.) The name of the offset for CET in Auto mode is `+02`, much less than the 8 character limit Nintendo has imposed. For CET right now, it should be `CEST,M3.5.0,M10.5.0`, which clearly far exceeds the 8 character limit we have and was causing the oob array access you observed.

Should be fixed in the new PR.
