### ISSUE TITLE
Error in last canary build

### ISSUE THREAD

**Issue by zemzema** [yuzu-emu/yuzu#1116]
Canary Build - 16943fb 

./yuzu
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
Qt Concurrent has caught an exception thrown from a worker thread.
This is not supported, exceptions thrown in worker threads must be
caught before control returns to Qt Concurrent.
terminate called after throwing an instance of 'std::logic_error'
  what():  Invalid hex digit
Aborted (core dumped)

**Comment by DarkLordZach** [comment]
This is an issue where the key file parser will forcibly fail when the key is not 32 hex digits long. It's a relic from testing. It should be fixed soon, but in the meantime make sure all of your keys and rights IDs are the correct length

**Comment by zemzema** [comment]
Checked everything, problem still exist. This is the first time that it's not working.

**Comment by Drive251** [comment]
@zemzema , it seem it was fixed

**Comment by DarkLordZach** [comment]
@zemzema I am confident that you have either: Incorrect length keys or a file in yuzu's nand not named properly. That is the only way to generate that error. The PR only prevents yuzu from hard crashing due to this.
