### ISSUE TITLE
Prince of Persia: The Lost Crown - Garbled cutscene skybox

### ISSUE THREAD

**Issue by EmulationEnjoyer** [yuzu-emu/yuzu#12703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1685

### Description of Issue

After the intro section of gameplay, during a real-time rendered cutscene, the skybox appears completely garbled/corrupted. **It may be the smoke effect that's causing this**

![pop_tlc_garbled_skybox](https://github.com/yuzu-emu/yuzu/assets/144477224/dbfd9a20-7660-4259-864c-f01e447bee59)

https://github.com/yuzu-emu/yuzu/assets/144477224/649c0ee9-e5a4-4168-917d-ec78f8efce22

- Using title update "1.0.2" / "17.0.1" system firmware
- Hashes and signature of game dump and title update are confirmed valid by NxFileViewer
- Setting accuracy to High does not resolve the issue
- Setting the graphics renderer to OpenGL does not resolve the issue (my default is Vulkan)
- Yuzu EA 4070 has the same issue
- Ryujinx does not suffer this issue

This seems to be the only issue with this game so far. Otherwise, after an hour or so of gameplay this is the only issue I've encountered and the game runs perfectly

### Expected Behavior

![pop_tlc_normal_skybox](https://github.com/yuzu-emu/yuzu/assets/144477224/ec7a8520-c1f1-45fb-b913-72443bc6bb58)

### Reproduction Steps

Occurs during the first cutscene after the intro section of the game - about 5 minutes in

1. Extract save files to save location
2. Launch the game and load the save
3. Affected cutscene will begin playing

Save location: `\user\nand\user\save\0000000000000000\<user_id>\0100210019428000\`

[pop_tlc_garbled_skybox_gamesave.zip](https://github.com/yuzu-emu/yuzu/files/13976910/pop_tlc_garbled_skybox_gamesave.zip)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13977082/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5 5600X
GPU/Driver: RX 5600XT / 23.5.2
RAM: 32GB 3200MHz
OS: Windows 10 (22H2)

**Comment by samusaran** [comment]
This is also present on Steam Deck so it seems it may not be a platform issue

**Comment by RaduNastase** [comment]
Could be that everyone uses the same dump which has an error in the movie file?

**Comment by plexecutor** [comment]
> Could be that everyone uses the same dump which has an error in the movie file?

I can dump my cart and report back. Won’t be able to do it until tomorrow at the earliest.

**Comment by EmulationEnjoyer** [comment]
> Could be that everyone uses the same dump which has an error in the movie file?

I purchase and dump my own games. Like I stated in my original post, hashes are valid and the issue isn't present in Ryujinx. This is an issue with Yuzu that applies to multiple graphics API's and apparently multiple platforms, so this is likely a core issue with Yuzu itself and I'm sure some devs have already seen this thread. Also, a majority of the cutscenes in this game are real-time rendered in-engine and not a video file

**Comment by RaduNastase** [comment]
> > Could be that everyone uses the same dump which has an error in the movie file?
> 
> I purchase and dump my own games. Like I stated in my original post, hashes are valid and the issue isn't present in Ryujinx. This is an issue with Yuzu that applies to multiple graphics API's and apparently multiple platforms, so this is likely a core issue with Yuzu itself and I'm sure some devs have already seen this thread. Also, a majority of the cutscenes in this game are real-time rendered in-engine and not a video file

I was under the impression that only that scene, which is a video file, is affected. Anyway, i don't have the game to test it myself, so it's like you say, an emulation issue.

**Comment by FirefoxinHell** [comment]
i have the same problem, it is not a problem with the dump, if you look at the video in detail on the console or in Ruyjinx, those videos have different layers of video, with transparency and I think there is the bug, yuzu is not emulating that type of combined videos well I think

**Comment by plexecutor** [comment]
> > Could be that everyone uses the same dump which has an error in the movie file?
> 
> I can dump my cart and report back. Won’t be able to do it until tomorrow at the earliest. That said this issue doesn’t exist in Ryujinx so I doubt it’s the dump.

I dumped my copy of the game and can confirm the video bug exists in all builds of yuzu I’ve tested. Steam Deck and Windows specifically. Mainline.

**Comment by samusaran** [comment]
It may have something to do with this comment, maybe: https://github.com/yuzu-emu/yuzu-mainline/commit/403fc86c1138821fac375a2ac850ac787969e2c8

I'm not skilled enough to fix any of this but hey, i had fun poking around

**Comment by Squall-Leonhart** [comment]
Probably fixed by https://github.com/yuzu-emu/yuzu/pull/12461

**Comment by heatguye** [comment]
I fixed it by disabling subtitles in the options menu of the game.

**Comment by EmulationEnjoyer** [comment]
> I fixed it by disabling subtitles in the options menu of the game.

Testing with Yuzu 1692, clearing the shader cache, and then disabling subtitles/subtitle background did not resolve the issue. Tested with Vulkan and OpenGL

**Comment by samusaran** [comment]
> Probably fixed by #12461

Can confirm that this PR does **not** fix the issue. It's slightly better, because at least the first frames are rendered correctly, but it gets worse and worse every couple of frames.

This is how that build renders the cutscene.
![immagine](https://github.com/yuzu-emu/yuzu/assets/290743/16cde3da-b068-4ce9-b0c8-45dab148359c)

**Comment by Squall-Leonhart** [comment]
that PR is a stepping stone to further improvements, its good that its current state got things to look better.

**Comment by GabrielModog** [comment]
I had this problem too. But it's the only problem presented in the game.

**Comment by jotesoft** [comment]
I am seeing the same problem. It may only happening in prerenderd cutscenes.

**Comment by DragonsFear** [comment]
traid it with the latest update (1.0.4), and latest yuzu version, and still have this problem :(

**Comment by Squall-Leonhart** [comment]
Please dont persist with the Me too's, when a fix is made this will be closed.

**Comment by salehif** [comment]
game update 1.0.5
yuzu 4144

problem still present
