### ISSUE TITLE
[android] Pokemon Violet still crashing on Yuzu 206

### ISSUE THREAD

**Issue by Rhouelyn** [yuzu-emu/yuzu#12784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 206 android

### Description of Issue

Still crash, i thought Pokemon Violet was fix on yuzu 206 but still crashing

### Expected Behavior

After 10min of gameplay fps starts to go down until it crash

### Reproduction Steps

Alot of crash happens on that log, first is when booting the game it crash alot when booting, then when i got ingame i can play like 10min before fps goes down and crash.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14047793/yuzu_log.txt.old.txt)

### System Configuration

CPU: Snapdragon 870
GPU/Driver: R12 beta extention agressive
RAM: 6gb ram
OS: android 13

**Comment by evil-trainer** [comment]
6GB RAM? That's your answer to your issue. You're using Yuzu with a device under the minimum specs required by the devs of Yuzu. No wonder you'll face these crashes. Pokémon Violet struggles to run even on real hardware, so it'll be even more unstable on an emulator for now 😅😅

**Comment by brujo5** [comment]
use zram or swap to avoid crashes for low ram

**Comment by jasmohan-narula** [comment]
Same issue happens on my Android phone with Snapdragon 888 and 12GB ram too

**Comment by brujo5** [comment]
i dont have crashes on my poco F4 8gb RAM and F5 12gb RAM

**Comment by liamwhite** [comment]
Fixed by #12869

**Comment by jasmohan-narula** [comment]
The issue is still there in Yuzu Android 222.

Pokemon Scarlet and Violet drop to 0 fps and crash.
