### ISSUE TITLE
[android] assassin Creed series not in-game 

### ISSUE THREAD

**Issue by M-hyun** [yuzu-emu/yuzu#12835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v213

### Description of Issue

old versions can go in-game....i tried all new versions and the game stopped going in-game starting from v213

### Expected Behavior

as always going in-game 

### Reproduction Steps

launch the title(rebel collection for example) select base game(black flag) ...wait for seconds till it's 0fps and exit the game...relaunch it again to be able to go in game.

### Log File

[ac2.log](https://github.com/yuzu-emu/yuzu/files/14078561/ac2.log)

### System Configuration

CPU:sd 855/ 860/870
GPU/Driver:a640/a650 both qq and turnip
RAM:8
OS: android 13

**Comment by liamwhite** [comment]
Can you get some videos of what you are observing as well as the expected behavior? I am struggling to understand what this issue report is trying to say

**Comment by liamwhite** [comment]
This genuinely looks like a bug in the old implementation. What happens if you just let it load?

**Comment by liamwhite** [comment]
Fixed in 220

**Comment by IrsyadLuffy** [comment]
But still can't start rogue tho. Even with merged nsp base+ dlc, using SAK and yanu, it's still stuck at 0fps.

**Comment by evil-trainer** [comment]
> But still can't start rogue tho. Even with merged nsp base+ dlc, using SAK and yanu, it's still stuck at 0fps.

Never ever use merged games. Yuzu devs already stated that Yuzu has issues with this. I had issues loading Pokémon VIolet exactly because of a merged game with an update.
