### ISSUE TITLE
Android touch controls not working 

### ISSUE THREAD

**Issue by xplodwild** [yuzu-emu/yuzu#13058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

20240217+

### Description of Issue

Hello

Since the 20240217 build, the onscreen touch controls don't seem to operate at all. I noticed the new "Controls" menu which marks all controllers disconnected and can't turn them on.

Tried to reset the overlay to no avail.

Thanks 

### Expected Behavior

Touch screen controls should work. 

### Reproduction Steps

Install any android build on or after 20240217, then start a game. I tried with Pokémon Let's Go Pikachu, works fine with 20240215 build, but since the new controls system, I can't get past the very first controller selection screen. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14321715/yuzu_log.txt)

### System Configuration

CPU: Google G2 (Pixel 7)
GPU/Driver: Mali
RAM: 8GB
OS: Android 14

**Comment by Skylance19** [comment]
Experienced this just now myself. Running yuzu version 254 and playing FFVI Pixel Remaster. Was unable to use the touchscreen keyboard when naming a character, verified all settings. Issue was fixed by rolling back to version 248.

**Comment by xplodwild** [comment]
@t895 Not sure if I'm missing something, but I still don't have working touch controls as of build 257 (today's)

**Comment by t895** [comment]
You can change the controller type of the touch controls by changing the type shown for player 1 in the Controls menu. I just tested myself and it's working as expected.

**Comment by xplodwild** [comment]
@t895 Okay, after further testing, I can indeed select the proper controller type in the build 256. However in build 257, the "Connected" switch won't turn on (it turns off immediately when I press the switch), hence I'm unable to select the controller type.

**Comment by t895** [comment]
That's a separate issue, but if you kill, yuzu, go to controls, preset the right control config, and then start the game, everything works.
