### ISSUE TITLE
Black Screen and Crash in any game.

### ISSUE THREAD

**Issue by wladgrsantos** [yuzu-emu/yuzu#1333]
Last Canary and Nightly build. 
Afterwhile open any game, the screen go black and Yuzu Crashes and close itself.
Log shows error on hw.gpu.

Nvidia GTX 1060 driver 399.24, Processor I5 - 8400, 16 GB Ram.

**Comment by DarkLordZach** [comment]
Which game?

**Comment by Hexagon12** [comment]
Please upload a full log file.

**Comment by ogniK5377** [comment]
Fixed with #1373 requesting to close

**Comment by Kokujou** [comment]
still not fixed... 
Game: I am Setsuna


[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2545377/yuzu_log.txt)

**Comment by Kokujou** [comment]
and btw: i recommend to compress logfiles just with the little feature of stacking the same errors and make them include the count they happen... like in this one the hex error... this'd reduce the sice from MB to B XD
