### ISSUE TITLE
Black Screen in Super Mario Odyssey After First Transition to Sand Kingdom

### ISSUE THREAD

**Issue by cjeee** [yuzu-emu/yuzu#1950]
Only tried it on canary 1750 and 1759, and it happened in both builds.

**Comment by DarkLordZach** [comment]
This is fixed in #1939, but you'll have to wait for that to be merged.

**Comment by Zeroksas** [comment]
Use canary 1464 or older version if you want to bypass softlock.

**Comment by Narugakuruga** [comment]
Sometimes this will result in not only softlock but also emulator crash. Tested in Canary 1779

**Comment by SiTWulf** [comment]
Same problem in Canary 1784

**Comment by DarkLordZach** [comment]
@Narugakuruga @SiTWulf again, you need to wait for #1939 to be merged for the softlock to stop

**Comment by Yvar192** [comment]
#1939 is now merged, so this issue should be fixed.

**Comment by Zeroksas** [comment]
It's not fixed. Yuzu now crashes instead of softlock when trying to access action guide.

**Comment by Narugakuruga** [comment]
Fixed in Canary 1810.

**Comment by Zeroksas** [comment]
yes it's fixed, but there is a bug. When loading action guide in full screen mode menu bar is not accessible. So it's not possible to close action guide and progress in game.

**Comment by FearlessTobi** [comment]
You should be able to close the action guide by simply pressing B. Also isn't it possible to just leave fullscreen mode for a second to use the button?

**Comment by Zeroksas** [comment]
No it's not working correctly. In fact in full screen mode keyboard is not responsive. I can only leave full screen mode by pressing Esc (F11 not responding) and even then I can't close action guide because I can't see menu bar as you can see in this picture:
![image](https://user-images.githubusercontent.com/44953731/50836909-4bb65f80-1352-11e9-8e4b-3d5de2440757.png)

**Comment by Hexagon12** [comment]
The original issue (black screen) is now fixed with #1939, please make new issues for any other reports.
