### ISSUE TITLE
Dragon Quest Builders - Graphic Issues + Crash log

### ISSUE THREAD

**Issue by MichalSy** [yuzu-emu/yuzu#2052]
Version: 5bc98c2 (2019-01-23)
Video: https://youtu.be/YStmp1b7I6o

The game starts on one notebook on the other it crashes! (see below)

---

The game starts with the following hardware:
CPU: Intel Core i7-7820HQ
GPU: NVIDIA Quadro M1200
RAM: 32GB
DISK: SSD

The main problems here are that the image is upside down and that many elements flicker.

---

On the following hardware the game crashes when loading:
CPU: Intel Core i7-6600U
GPU: NVIDIA Geforce 940M
RAM: 16GB
DISK: SSD

Logfile: https://pastebin.com/qXZCM9K1

**Comment by Hexagon12** [comment]
Please provide a full log, and not a cutout.

**Comment by MichalSy** [comment]
Which service do you use to upload large log files?
I have now uploaded it to Google:

https://drive.google.com/open?id=1Q02dilv3sqwebOWVWdy9SI6SYB5RsSNC

**Comment by Hexagon12** [comment]
Does the issue still happen on the latest Canary?

**Comment by MichalSy** [comment]
Game doesn't start anymore:

[ 132.871218] HW.GPU <Error> video_core\gpu.cpp:CallPullerMethod:219: Special puller engine method Unk2c not implemented
[ 132.871330] Debug <Critical> video_core\renderer_opengl\gl_rasterizer.cpp:ConfigureFramebuffers:505: Assertion Failed! Unimplemented code!

**Comment by ReinUsesLisp** [comment]
This games is written using legacy OpenGL features, which is surprisingly an actual hardware feature in Nvidia's Maxwell GPUs. We have two approaches to implement the functionality required for this game to work:
- Emulate it in a "standard" way using OpenGL core profile.
- Doing close to 1:1 emulation with OpenGL compatibility profile.

The later is easier to do and probably faster on capable OpenGL drivers, but it has all the drawbacks of using OpenGL compat and the solution can't be easily ported to other APIs like Vulkan.

For the record, the game is using GLSL code that uses `gl_MultiTexCoordN` and old trash like that.

**Comment by MichalSy** [comment]
So that sounds like it never worked? But that can't be confirmed with my video. So there was once a version that also worked in-game and it didn't look so bad.?

**Comment by nickkeane** [comment]
Getting a messed up main menu and tinny sound. Pressing + gives a largely transparent box. Pressing A shows box with "Setting" and "Customis Characte" with smudged glyphs at the end, and transparency.

https://drive.google.com/file/d/1QzPswzcdRw3es9ShnuNMQtCwVlYXQecM/view

**Comment by NineKain** [comment]
Same problem as above ^

**Comment by MysticExile** [comment]
![010008900705c000_2022-03-27_20-25-24-160](https://user-images.githubusercontent.com/30736337/160295260-a046bb27-7f93-48f8-8736-40698611daa8.png)

The game works fine, the UI however is still bugged and nearly invisible.

**Comment by bunnylin** [comment]
The September Yuzu progress report showed DQB running fine and showing the textboxes correctly, but I guess that was on NVidia OpenGL. I can confirm that, same as the previous comment, the textboxes appear nearly invisible for me on the latest mainline build right now. I'm using a Radeon RX550, AMDGPU on an up-to-date Archlinux. Changing between Vulkan and OpenGL rendering in Yuzu doesn't seem to matter, so I assume it's a problem either somewhere in Mesa or the open-source AMD drivers.
![dqbyuzu](https://user-images.githubusercontent.com/17849472/199075613-065f568c-e1c7-4f53-9d5e-b55183d13158.jpg)

**Comment by bunnylin** [comment]
With recent mainline builds, DQ Builders is fully playable! I've gotten all the way to the final chapter's last battle, but there's a visual glitch that I can't seem to avoid there. Some special effects have a chance of turning the screen mostly blue, as pictured. The game keeps running, but it's like most polygons are rendered in a uniform flat blue. Some sprites are still drawn normally.
![dqb_blue](https://user-images.githubusercontent.com/17849472/209084431-57eb655b-3ec0-4a11-9b1d-a51fbddde694.png)

This happened randomly when a large frost hand did some particular magic attack in the third chapter, and is happening seemingly every time when I run up to the Dragonlord encounter at the end game. Standard output from Yuzu doesn't print anything when this blueness befalls.

**Comment by vtmarik** [comment]
Some of the 3d objects appear/disappear based on the camera angle, even a small change can make objects appear/disappear. Some like doors and workbenches stay invisible almost the entire time.
![010008900705c000_2022-12-28_14-24-15-606](https://user-images.githubusercontent.com/13528996/209862515-54b2adf1-211d-43c7-9574-dab3f48bca2c.png)
![010008900705c000_2022-12-28_14-24-24-059](https://user-images.githubusercontent.com/13528996/209862521-0e178092-88a8-44ad-9a83-3b9bea7dc6d7.png)
![010008900705c000_2022-12-28_14-24-07-458](https://user-images.githubusercontent.com/13528996/209862529-c447a7da-a53e-4263-bebd-ad6671430cf6.png)

**Comment by nickkeane** [comment]
Using Yuzu Early Access 3514, looks like the interface is fixed and everything is going well so far.

**Comment by bunnylin** [comment]
I've built anew from mainline just now and tried the final battle again. Unfortunately, the blue screen visual glitch still happens there, so the game remains unwinnable on my system...

**Comment by CodeTappert** [comment]
I tried this today with yuzu EA 3754. And after entering my name the game goes to 0fps. Is there a special setting i need to use?

**Comment by nickkeane** [comment]
Try changing the graphics api

**Comment by TerrorPeter** [comment]
Trying out all the different available graphic APIs did not seem to solve the problem. DQB still crashes on launch for me. I have attached 3 different logs. They all show the same problem: <Critical> video_core/texture_cache/image_info.cpp:operator():65: Assertion Failed!
[GLASM yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12410438/GLASM.yuzu_log.txt)
[GL yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12410440/GL.yuzu_log.txt)
[VULCAN yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12410441/VULCAN.yuzu_log.txt)

**Comment by bunnylin** [comment]
I'm happy to report with the current mainline (mainline-0-1560, commit 492e81f1fdb), the blue visual glitch is no longer apparent, and I was able to beat the game!

![dqb_fixed](https://github.com/yuzu-emu/yuzu/assets/17849472/9bb5b332-2451-4189-8b00-a21c2dce1041)

However, there are now other rendering errors, such as people's eyes, or these no longer green bushes...

![dqb_bushes](https://github.com/yuzu-emu/yuzu/assets/17849472/c2a3e966-b2c9-48f4-a145-4584987383ce)

**Comment by bunnylin** [comment]
I'm extra happy to report I was able to play all the way through Dragon Quest Builders from beginning to end without any showstopper problems, on Yuzu master-mainline-636-13571, commit cc81801cd. Only visual glitch I noticed now is that shadow rendering can look glitched from some camera angles, but it's pretty minor.
