### ISSUE TITLE
pfba crash with Xbyak error (with dynarmic)

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#218]
## Hardware specs :
- Nvidia GeForce GTX 960
- AMD FX-6300
- 8 GB Of Ram
- Windows 7 Pro

## Issue :
when i run the homebrew pfba yuzu after couples of seconds crash with

"Terminate called after throwing an instance of 'Xbyak::Error'
what(): label is too far
This application has resquested the runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

## Log :
the major part of the log because there is a bug causes the non-fully registration of the log with the command "yuzu.exe 2> log.txt"
[Click Here](https://gist.github.com/greggameplayer/c8931afccd74b970c868a8d122167374)

**Comment by Cpasjuste** [comment]
Hi, this error was not present a few days ago. I'm not sure if this comes from a libnx change or a yuzu change.

**Comment by greggameplayer** [comment]
ok, so can you correct that please ?

**Comment by Cpasjuste** [comment]
No, this is probably out of my knowledge (and time).

**Comment by Hexagon12** [comment]
@MerryMage should be working on a fix for this, since I sent the proper stack trace and debugging info a while back.

**Comment by greggameplayer** [comment]
@Hexagon12 thanks for the information

**Comment by jroweboy** [comment]
We just pushed a fix for this. Please retest

**Comment by Hexagon12** [comment]
This issue is now fixed.

**Comment by Cpasjuste** [comment]
Hi, tried today, it seems the problem still exist : 

terminate called after throwing an instance of 'Xbyak::Error'
  what():  label is too far
Abandon (core dumped)

**Comment by jroweboy** [comment]
@cpasjuste make sure you update your submodules as it's a crash in dynarmic

**Comment by Cpasjuste** [comment]
Yep, cloned the repo "from scratch", I'll take a closer look.

Le mer. 28 mars 2018 à 16:00, James Rowe <notifications@github.com> a
écrit :
