### ISSUE TITLE
Mario Odyssey graphic glitch in the folding screen found in bowsers kingdom

### ISSUE THREAD

**Issue by MultiCuriousKitty** [yuzu-emu/yuzu#2475]
Hi I am using Yuzu Canary Build 2261 HEAD - 68aaf6f (2019-05-14) I have been playing Super Mario Odyssey without too much trouble apart from motion controls up to now but this graphic screen glitch I have come across is preventing me from completing this part of the game which offers two power stars. I have attached a picture. It reminds me of the ending effect of a game of solitaire on the old pc and it gets worse every time I die and return. The stages of the folding screen seem to be getting mixed together too as a result of this which makes it almost impossible to navigate the platforming for me. Can we fix this? Any help would be appreciated.
![glitch folding screen](https://user-images.githubusercontent.com/47960838/57892210-7de84880-7881-11e9-95ec-3fc927513c45.png)

<meta name="titleids"  content="0100000000010000">

**Comment by fluffapparition** [comment]
Something is wrong with the way it clears the screen, probably masking or render textures, not sure since I dont know how 2D sections of Mario Odessy are build but it definitely looks like canvas clearing isn't working on that section.

**Comment by fluffapparition** [comment]
Can you update Yuzu and see if that fixes anything? Found an article that describes them fixing these issues already 

https://yuzu-emu.org/entry/yuzu-progress-report-2018-p4/

**Comment by Tabby4675** [comment]
I played that section and didn't had any issues

**Comment by fluffapparition** [comment]
@tabby4675 what build were you using?

**Comment by MultiCuriousKitty** [comment]
Thank you everyone for your response to my issue. I'm sorry I was slow to answer any of you. I am using Yuzu Canary Build 2384 HEAD 3935b88. I have just gone through a huge update and the graphics have become worse. See picture attached. Thank you for the article link @fluffapparition . I realised that other graphical issues I had been having throughout the game were linked together with this issue. Can you change the build without effecting your saved games?
![graphics worse](https://user-images.githubusercontent.com/47960838/61196925-36f9c080-a715-11e9-97b3-f2084e7eac83.png)

**Comment by MultiCuriousKitty** [comment]
I just downloaded and Installed Canary Build - 314c179
The graphics have gone back to what I started with then I died and they looked like the attached picture. Now what?
![graphics still bad](https://user-images.githubusercontent.com/47960838/61198604-0c603580-a71e-11e9-860e-0ff94654fb03.png)

**Comment by FernandoS27** [comment]
Fixed by #2735 .

**Comment by Hexagon12** [comment]
The issue is not solved. The proposed PR is not merged yet.

**Comment by MultiCuriousKitty** [comment]
Definitely not fixed. This is still an issue
![not fixed](https://user-images.githubusercontent.com/47960838/61324338-86dfa100-a855-11e9-985d-42360efc03de.png)

**Comment by FernandoS27** [comment]
The pr is not in canary yet.

**Comment by Tabby4675** [comment]
Working fine for me on an HD 510, it never broke for me. Below are the screenshots I took on that day's latest Canary.
![Screenshot_1](https://user-images.githubusercontent.com/44977987/61477079-1b5c1780-a9ac-11e9-9284-f8206b714eb6.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/44977987/61477082-1c8d4480-a9ac-11e9-89fc-7f08a595fb5b.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/44977987/61477083-1d25db00-a9ac-11e9-9d3b-b93b1df80e09.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/44977987/61477084-1e570800-a9ac-11e9-9847-796d8c149b2c.jpg)

**Comment by fluffapparition** [comment]
Other gpus? @Tabby4675
