### ISSUE TITLE
Weird Shades in Zelda Breath of The Wild + Photo

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#2554]
As soon as you get out of the cave in Zelda Breath of the Wild, you get this shade 
![1234](https://user-images.githubusercontent.com/51413997/59015863-a348f080-8848-11e9-98a3-4982a0b69272.png)

<meta name="titleids"  content="01007EF00011E000">

**Comment by BSoDGamingYT** [comment]
This is a known bug, which will be fixed in the upcoming texture cache rewrite.

**Comment by MysticExile** [comment]
This issue has been fixed by PR [#2601](https://github.com/yuzu-emu/yuzu/pull/2601)

**Comment by wangyan-life** [comment]
It still exists in yuzu EA 3446 now.
[https://i.postimg.cc/G3Mjz6kY/1.png](url)
![1](https://user-images.githubusercontent.com/105880463/226818701-9e18a8f7-78da-4eac-8452-2776bdac1f6f.png)

**Comment by roguesuspect** [comment]
I am also having this issue when running in vulkan with EA 3531

**Comment by Cheezeburgerstick** [comment]
I am also getting this issue. Running in Vulkan with a 7900XTX, 3x Scale (changing this doesn't appear to help) SMAA and High Accuracy (Extreme doesn't appear to change anything either). It seems to be an issue with the Vulkan API as the black textures don't appear on the OpenGL API, though there are other performance issues when using it.

**Comment by roguesuspect** [comment]
> I am also getting this issue. Running in Vulkan with a 7900XTX, 3x Scale (changing this doesn't appear to help) SMAA and High Accuracy (Extreme doesn't appear to change anything either). It seems to be an issue with the Vulkan API as the black textures don't appear on the OpenGL API, though there are other performance issues when using it.

Yeah I am running a 7900 XT. I've tried turning on and off a bunch of various settings with no luck. The issue does not exist in open gl but the game is not playable in open gl for me.

**Comment by elnoelsi** [comment]
have you guys tried using "Default" Anisotropic Filtering? I was playing with settings and i believe changing that one was giving me similiar issues

**Comment by cHunter789** [comment]
> have you guys tried using "Default" Anisotropic Filtering? I was playing with settings and i believe changing that one was giving me similiar issues

This is it! Thank you!

**Comment by asayasobhi** [comment]
> have you guys tried using "Default" Anisotropic Filtering? I was playing with settings and i believe changing that one was giving me similiar issues

it's work. Thank you.
