### ISSUE TITLE
Stopping and restarting emulation causes yuzu to crash

### ISSUE THREAD

**Issue by Eloeri** [yuzu-emu/yuzu#2785]
When stopping emulation manually through the tool bar and then restarting emulation/restarting the game causes yuzu to crash.

**Comment by fluffapparition** [comment]
Rip

**Comment by FearlessTobi** [comment]
Caused by https://github.com/yuzu-emu/yuzu/pull/2364.

**Comment by Morph1984** [comment]
Is this really caused by #2364? It was never merged to canary so it was never tested.

**Comment by FearlessTobi** [comment]
this has been in Canary for multiple months now

**Comment by FearlessTobi** [comment]
Also shows error message: 

`Debug <Critical> core\hle\kernel\scheduler.cpp:SwitchContext:348: Assertion Failed! Thread must be ready to become running.`

**Comment by MysticExile** [comment]
This issue appears to have been fixed! If there are any further problems regarding this issue, please feel free to open a new issue.

**Comment by zyzkevin** [comment]
still happening on EA 1180
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5631040/yuzu_log.txt)

**Comment by neonoafs** [comment]
Still happening with the latest version 719
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7004168/yuzu_log.txt)

**Comment by RinMaru** [comment]
Still happening in build EA 1995

**Comment by Kane-Kuroneko** [comment]
Still exists in Date 2023-12.
