### ISSUE TITLE
src/video_core/buffer_cache/buffer_cache.h: Missing include?

### ISSUE THREAD

**Issue by Cleverking2003** [yuzu-emu/yuzu#2821]
I'm building Yuzu on Ubuntu 19.04 with GCC 9.1.0. It gives me this error:

> /home/cleverking/yuzu/src/./video_core/buffer_cache/buffer_cache.h:267:34: error: «make_iterator_range» is not a member of «boost»
  267 |         for (auto& pair : boost::make_iterator_range(mapped_addresses.equal_range(interval))) {
      |     

It looks like there's a missing include. When I add #include <boost/range.hpp>, Yuzu compiles normally.
[build_log.txt](https://github.com/yuzu-emu/yuzu/files/3558846/build_log.txt)

**Comment by FernandoS27** [comment]
Should be fixed now, try updating.

**Comment by Cleverking2003** [comment]
Unfortunately, the issue is still here.
[build_log.txt](https://github.com/yuzu-emu/yuzu/files/3562186/build_log.txt)

**Comment by Hexagon12** [comment]
Is the issue still present?

**Comment by ObscenityIB** [comment]
> Is the issue still present?

I also had the same error just now, so it indeed is.

**Comment by FearlessTobi** [comment]
Could you try opening a PR to fix it?
