### ISSUE TITLE
Yu-Gi-Oh Legacy of the duelist link evolution issues

### ISSUE THREAD

**Issue by Komoneythescrub** [yuzu-emu/yuzu#3146]
Two main problems when runnin the game on Yuzu:
The card text (box) is empty and the occurring black screen when summoning ace monsters (when 3d 
animations should pop up). Maybe caused by the 3d rendering of some monsters.

![Screenshot_1](https://user-images.githubusercontent.com/58013111/69287994-d87faa00-0c00-11ea-96d1-744317281c37.png)

**Comment by BSoDGamingYT** [comment]
This game uses videos not rendered 3D for its battle animations. NVDEC (Video decoding) is not currently supported on yuzu. This issue is already known & reported

**Comment by Komoneythescrub** [comment]
Sorry for the repeat then. But what about the empty card description boxes, like the one in the pic?

**Comment by ReinUsesLisp** [comment]
The empty card description could be stencil being broken. A few games like Smash Ultimate and Cadence of Hyrule have issues with this.

**Comment by ReinUsesLisp** [comment]
Tracked down the issue. It's scissor's y being flipped.

**Comment by Komoneythescrub** [comment]
> 
> 
> Tracked down the issue. It's scissor's y being flipped.

Well done! Hope that it will get fixed soon!!

**Comment by Komoneythescrub** [comment]
https://www.youtube.com/watch?v=tTHmwTNnXRc . It's strange that this guy playing the cards with attack animations without ANY black outs. How come? As we can see he is playing at a quite high speed too.

**Comment by DarkShadow44** [comment]
While probably not the correct fix, I'm attaching a hack that should fix the issue:

[0001-Hack-to-fix-scissor-issue.patch.txt](https://github.com/yuzu-emu/yuzu/files/4024539/0001-Hack-to-fix-scissor-issue.patch.txt)

**Comment by ReinUsesLisp** [comment]
As a small update, I'm waiting for Vulkan to be in master to open a pull request to rework the state tracker. After that I can fix this issue (otherwise it would generate conflicts).

**Comment by arafat1991** [comment]
come on guys please can anyway fix the empty card description text ? its really annoying :( .

**Comment by DarkShadow44** [comment]
@arafat1991 I attached a patch, didn't I?

**Comment by arafat1991** [comment]
@DarkShadow44 im sorry i have no idea how to install things or tinker with yuzu im completely newbie :(

**Comment by arafat1991** [comment]
@DarkShadow44 i downloaded ur patch but i didnt know where to put it or what to do, so can you help me please where should i install it or any helpful tips ?

**Comment by DarkShadow44** [comment]
@arafat1991 This is not a support forum. You need to apply the patch and compile from source, which takes a bit of knowledge, or just wait until it's properly fixed.

**Comment by arafat1991** [comment]
@DarkShadow44 thank you and sry to bother you guys i guess will have to wait for a proper fix for noobs like me.

**Comment by MelvinFrohike24** [comment]
![espejo](https://user-images.githubusercontent.com/61917262/76150377-2df59f00-60aa-11ea-8507-ee712d8f2fe5.PNG)

hello, I am testing the vulkan version and it works great, the texts of the letters are seen perfectly but the screen looks in mirror mode

**Comment by Anuskuss** [comment]
I don't know if that report from last year is still accurate, but for me the game is extremly broken (upside down, broken textures, big artifacts). The last version where it worked perfectly is `yuzu-mainline-636-1230` and [DarkShadow44's patch](https://github.com/yuzu-emu/yuzu/issues/3146#issuecomment-570985077). Everything (except the upside-down view) could be my iGPU's fault though.

**Comment by Anuskuss** [comment]
Alright, the orientation is fixed now and most of the garbage on screen is gone (as of #6765), but the textures are still broken. I've managed to track down the first bad version ([v491](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-491)), but was having trouble building the separate commits, so this has to do for now. If I had to take a guess here I'd point at #4967, specifically (just based on how it looks, although it's broken in the same way in OpenGL):

> Rendering to texture views of a different format is emulated as it should be, drivers that fail to do this properly (Intel and AMD’s proprietary drivers) won’t render properly and there are no intents to fix it on our end.

@MelvinFrohike24 Can you confirm that it's working for you? Also what GPU do you have?

**Comment by ZEXERJK** [comment]
> So apparently #7219 is supposed to fix the card bug, but I can't get in-game because it crashes right after the intro (Intel iGPU).

My Setup:
GPU: Nvidia 1080
CPU: Intel i7-8700K
Yuzu version: EA2260
Game version: 1.0.1(latest)

Unfortunately even on the latest build of Yuzu Early Access the problem and graphical glitches about the cards still persist, so I doubt that the new Mainline build even with Project A.R.T. #7219 will fix anything.
Since @FernandoS27 is the person that posted about Project A.R.T. and said: “We also added FXAA in an Anti-Aliasing pass, and fixed some of TCR's regressions like blur in the Bayonetta 2's cutscenes, blur in Pokémon Sword/Shield cutscenes on AMD/Intel drivers, and **_Yu-Gi-Oh!: Legacy of the Duelist's cards not rendering_**.” can probably update us all about the fix not working or if something is being done on this matter.
Thank you.

**Comment by DarkShadow44** [comment]
Attaching updated hack for the text issue.
[0001-Hack-for-text-issue.patch.txt](https://github.com/yuzu-emu/yuzu/files/7707758/0001-Hack-for-text-issue.patch.txt)

Textures of the cards are still a mess though, might or might not try to bisect that issue for another hack.

**Comment by Anuskuss** [comment]
> might or might not try to bisect that issue for another hack.

@DarkShadow44 I already [tried that](https://github.com/yuzu-emu/yuzu/issues/3146#issuecomment-890649765) and it's somewhere in [Project ART](https://github.com/yuzu-emu/yuzu/pull/4967) but I couldn't build any specific commits. Good luck if you'd still like to try though.

**Comment by DarkShadow44** [comment]
I used the following patch to build the commits:
[0001-HACK-fixed.patch.txt](https://github.com/yuzu-emu/yuzu/files/7741258/0001-HACK-fixed.patch.txt)

So, the worst offender here is 9764c13d6d2977903f407761b27d847c0056e1c4.
It's way too huge and messy to simply revert though.

**Comment by Anuskuss** [comment]
Texture issue has been fixed. The only thing remaining is the missing text. I don't remember if https://github.com/yuzu-emu/yuzu/issues/3146#issuecomment-993044390 fixed that but I know that https://github.com/yuzu-emu/yuzu/issues/3146#issuecomment-570985077 did. Applying `0001-Hack-for-text-issue.patch` now doesn't do anything.

**Comment by AnimeHeaven** [comment]
Sorry to reopen this issue but on the steam deck the problem is still there. No graphic on some cards, card graphic glitches on the „chest“ and on the field and no text in the description.

I tested it with OpenGL and Vulkan and both have the same issue…

On the picture I tested it with streched window but it is on 16:9 too…

![image](https://github.com/yuzu-emu/yuzu/assets/40724489/7d0627b1-e49d-46f5-ae19-26530d2e211f)

**Comment by rospec14** [comment]
Will this ever get fixed? It's been here for four years.
