### ISSUE TITLE
LayeredFS on Pokemon Mystery Dungeon:DX Results in Unmapped Memory Read on Boot

### ISSUE THREAD

**Issue by NarryG** [yuzu-emu/yuzu#3482]
When applying a LayeredFS (tested both RomFS, ExeFS ips, and ExeFS normal) to PMD:DX, the game fails to boot. This is independent of any modifications to the files. Without a LayeredFS patch applied, the game boots fine.  
This appears to be isolated to purely LayeredFS, not patching in general, as the game is able to boot fine with the official 1.0.1 NCA patch installed to nand. I've also tested LayeredFS against another game and had no issues there, so it appears to be linked to PMD:DX in some way.

**Version**: HEAD-mainline-636-1224-gf1fb4b283
**Log**: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4301980/yuzu_log.txt)

**Steps to Repro:**
Create a mod folder. (yuzu/load/01003D200BAA2000/TestMod)
Create a `romfs` folder within your mod folder
Copy any file from the base-game to the `romfs` folder (example would be boot.config from the root directory)
Enable the mod in Yuzu
Boot the game

**Expected result**: The game loads with the modded file.

**Actual result**: The game fails to load, the log is filled with unmapped memory assertions. These assertions are always the same between runs.
```
[  19.600266] Core.ARM <Info> core\arm\dynarmic\arm_dynarmic_64.cpp:InterpreterFallback:69: Unicorn fallback @ 0x9662F14 for 1 instructions (instr = E7FFDEFE)
[  19.600274] Debug <Critical> core\arm\unicorn\arm_unicorn.cpp:UnmappedMemoryHook:59: Assertion Failed! Attempted to read from unmapped memory: 0x9662F14, pc=0x9662F14, lr=0x9662F14
[  19.600280] Debug <Critical> core\arm\unicorn\arm_unicorn.cpp:ExecuteInstructions:174: Assertion Failed! Call uc_emu_start(uc, GetPC(), 1ULL << 63, 0, num_instructions) failed with error: 8 (Invalid memory fetch (UC_ERR_FETCH_UNMAPPED))
```

**Comment by theboy181** [comment]
https://github.com/yuzu-emu/yuzu/issues/3206

it seems to be any type of file put into the load directory - There are many games that have this same issue, I didn't link the issue to Unity Games specifically though.

**Comment by NarryG** [comment]
> #3206
> 
> it seems to be any type of file put into the load directory - There are many games that have this same issue, I didn't link the issue to Unity Games specifically though.

I know for sure that every game on that list besides Bubble Bobble 4 and OBAKEIDORO are Unity, and I'd hedge my bets that those two games are also Unity.

**Comment by enler** [comment]
I think I fixed it, you can try to use layeredfs with the lastest build version from here  https://github.com/yuzu-emu/yuzu-mainline/releases

**Comment by IceLancerSR** [comment]
> 
Hello. I had a crash with LayeredFS #8798 
It's safe to assume it's not fixed. I know couple years too late , but nevertheless

**Comment by Nidelon** [comment]
I have the same error in Pokemon Shield, when I try to log into Circhester stadium, the log was cyclically clogged in my old versions, after the update it now gives this:
[ 187.798603] HW.Memory <Error> core\memory.cpp:operator ():571: Unmapped Read64 @ 0x0000000000000000
[ 187.798639] HW.Memory <Error> core\memory.cpp:operator ():571: Unmapped Read64 @ 0x0000000000000010
[ 187.800075] Core.ARM <Critical> core\arm\dynarmic\arm_dynarmic_64.cpp:ExceptionRaised:147: Cannot execute instruction at unmapped address 0x00000000000000
