### ISSUE TITLE
Graphical glitches after Yuzu 192 update

### ISSUE THREAD

**Issue by GodKratos** [yuzu-emu/yuzu#3495]
I've been playing Links Awakening perfectly fine for the last few days but today when I ran the game there were some strange graphical issues that have never happened before.

To start with, the start screen did not show up and remaing a black screen but I could hear the theme music playing in the background. I then pushed L+R and kept hitting A until my save game loaded.
After the game loaded and I was in catfish maw dungeon there were all sorts of graphic overlays flickering all of the screen (including an image of some character flashing across the screen. Changing screens to a different room created strange white flashing around the outside of the room. Walking outside, everything looked fine but back in the dungeon the graphical anomalies returned.

I'm currently on yuzu 192 which shows HEAD-mainline-636-1307-gdaf658c4d (2020-03-10) in the about menu.
Everything was fine last night so it must be something in the 192 update just released.

Using OpenGL API, disk shader cache enabled, asynchronous GPU emulation enabled, Native resolution and default aspect ratio. Only vsync enabled in advanced graphic settings.

**Comment by BSoDGamingYT** [comment]
This is already reported and fixed with PR 3494

https://github.com/yuzu-emu/yuzu/pull/3494

**Comment by roger6325** [comment]
I have test mainline 192-194, the failure symption is not fixed AMD GPU, same as:
[https://github.com/yuzu-emu/yuzu/pull/3494](url)
In the yuzu Early Access build 20200312-3d7983e95 (265), the ZLA start screen graphical still glitches both on the OpenGL and Vulkan (Device:  AMD Radeon Pro 555 )

**Comment by GodKratos** [comment]
This issue does not occur with Vulkan for me, only with OpenGL.

**Comment by roger6325** [comment]
In the yuzu Early Access build 20200314-6fb6cd781 (276), the ZLA start screen graphical still glitches both **only on the OpenGL** (Device: AMD Radeon Pro 555 ). 
Vulkan also for me on version 276. here it is.
![註解 2020-03-15 090533](https://user-images.githubusercontent.com/7112171/76693201-39455d80-669c-11ea-9230-70b3748ff543.png)

**Comment by roger6325** [comment]
The ZLA start screen graphical glitches is gone on both only on the OpenGL Vulkan on version 238 (Device: AMD Radeon Pro 555 )

**Comment by MysticExile** [comment]
@GodKratos @roger6325 Can any one of you confirm if the issue is still there?

**Comment by GodKratos** [comment]
I just tested this on Yuzu 417 and it seems a lot better than before.
There are still flickering shadow glitches in the trees (as in SS below) but the flashing images in the dungeons have gone.
Still Vulkan looks a lot better than OpenGL, it's a pity it's not as stable for me.

Vulkan:
![image](https://user-images.githubusercontent.com/692616/97081664-585b9300-1660-11eb-9af1-952db6c899e9.png)

OpenGL:
![image](https://user-images.githubusercontent.com/692616/97081672-6a3d3600-1660-11eb-96fc-cbf9bb7e78b5.png)
