### ISSUE TITLE
Animal Crossing: New Horizons Game hangs on item customization

### ISSUE THREAD

**Issue by rdude** [yuzu-emu/yuzu#3951]
This bug was present using an RTX 2080 Super in Vulkan. EarlyAccess Build.

By storyline I should customize item. But when I select customization, and when game should draw customization menu, game freeze.

Workaround. I switch render library from Vulkan to OpenGL, and game not hangs on customization menu.
But OpenGL is working slower then Vulkan.

Thank you in advance!

**Comment by Raquaa** [comment]
I have the same issue: running Vulkan on a Ryzen 5 2600 + RX 580 with 16gb ram.

**Comment by icanotc** [comment]
same here, vulkan + rx580 + i5 6600 +32gb ram

it's on yuzu 352, IDK if it's fixed in EA, since I don't have access to it.

**Comment by icanotc** [comment]
tried EA + opengl, still doesnt work

**Comment by DanMossa** [comment]
Bug still exists using the latest Yuzu with the tcr implemented.

**Comment by lat9nq** [comment]
Occurs on OpenGL that is not NVIDIA and any Vulkan driver
