### ISSUE TITLE
No audio through a USB-connected Dualshock 4 v2's headphone jack

### ISSUE THREAD

**Issue by zwammetje** [yuzu-emu/yuzu#4533]
On mainline Yuzu (20200814-f0d7a3dbf), audio does not output through a Dualshock 4 v2 connected through USB. When you plug in a headphone through the DS4's headphone jack, Windows 10 recognizes this as "Headset Earphone". Windows noises, Firefox, and Spotify all work. Yuzu does not output anything through it, regardless of chosen device in its own settings (e.g. Windows is set to the DS4 headphone jack with Yuzu on "auto", or the actual device in Yuzu).

Drivers are stock (as installed by Windows on first plug-in of the controller).

**Comment by ShyCode-analyst** [comment]
HI, do you have a LOG ?

**Comment by v1993** [comment]
Do you have the same problem with other emulators that use Cubeb for audio output, especially Citra? Because it's not very likely that Yuzu is one to blame here as far as I can guess.

**Comment by Alicanto** [comment]
I have the same problem with the latest update (mainline-636-5330).
Audio works through the main speakers, but not from the PS4 controller connected via USB. 
Also, if I change the sound device on Windows while the game is running (from the controller to speakers) I still get no audio. I have to restart the emulation.

**Comment by reichembach** [comment]
Was having this problem for a while now as well. Decided to test Citra as per @v1993 's comment and can confirm it also does not work

**Comment by v1993** [comment]
It would also be pretty useful to see if Firefox browser also have this problem, since it also uses Cubeb and both are developed by Mozilla (so we can mostly assume Firefox uses Cubeb correctly). This would help with finding out if it's Yuzu/Citra misusing Cubeb API or bug in Cubeb itself.

**Comment by boraaydogan** [comment]
Audio on Firefox is fine. Interestingly, Dolphin emulator also has this problem.

**Comment by v1993** [comment]
@boraaydogan Dolphin have both WASAPI and Cubeb audio backends (maybe some other ones too, dunno). Does it happen on all of them?

**Comment by boraaydogan** [comment]
When I try WASAPI, I'm getting this: Your current audio device doesn't support 16-bit 48000hz PCM audio. WASAPI exclusive mode won't work.

On cubeb there is no error message

**Comment by boraaydogan** [comment]
DS4 v2 seems to only support 16-bit 32000Hz. Maybe the problem with Cubeb is somehow related. By the way I got sound with OpenAL backend on Dolphin, had to install it first though.

**Comment by v1993** [comment]
Well, Cubeb uses WASAPI internally, so it *may* be a related issue. I'm afraid I won't be able to help much further with this issue since someone with better knowledge of WASAPI/Cubeb/Windows is needed.

**Comment by CrusadingNinja** [comment]
At least with Dolphin, this got fixed by updating cubeb to the latest version in externals (see https://bugs.dolphin-emu.org/issues/12315) so it may be a similar situation for Yuzu.

**Comment by reichembach** [comment]
Confirming audio now works with sdl2. Cubeb still not working, but at least we have an alternative :)

**Comment by german77** [comment]
> At least with Dolphin, this got fixed by updating cubeb to the latest version in externals (see https://bugs.dolphin-emu.org/issues/12315) so it may be a similar situation for Yuzu.

We are using a more recent version of cubeb than dolphin

**Comment by liamwhite** [comment]
Please comment if this is still relevant, as it may have been fixed by the recent audio rewrite
