### ISSUE TITLE
Crash Team Racing black squares on screen (Mesa)

### ISSUE THREAD

**Issue by C1fer** [yuzu-emu/yuzu#4694]
This happens on many tracks using OpenGL on both EA and Mainline. A weird dot pattern can be seen on the third screenshot too (this also happens on many tracks.)

OS: Arch Linux
CPU: Ryzen 5 1600
GPU: RX 480 (mesa-git 20.3.0 128402.27516baa2ae-1, LLVM-git 12.0.0 r366566.13e19d2e7cdc-1)
RAM: 16GB

![Screenshot_20200921_094134](https://user-images.githubusercontent.com/41005657/93775424-61d08600-fbf0-11ea-82a4-238f1775ffc3.png)
![Screenshot_20200921_095006](https://user-images.githubusercontent.com/41005657/93775429-62691c80-fbf0-11ea-9c4e-6b6aff4057b2.png)
![Screenshot_20200921_095717](https://user-images.githubusercontent.com/41005657/93775805-dc010a80-fbf0-11ea-838e-3c991801215a.png)

**Comment by FearlessTobi** [comment]
This is missing a log file.

**Comment by C1fer** [comment]
Didn't read the message until today. Here it is
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5282579/yuzu_log.txt)

**Comment by Illidan1943** [comment]
Also happens on Windows, tried several drivers on both OpenGL and Vulkan, nothing changed, here's the log using latest drivers and Vulkan

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5322384/yuzu_log.txt)

**Comment by carlosruan12307** [comment]
this happens to me too, did anyone get any solution?

**Comment by Illidan1943** [comment]
Still the same problems

**Comment by titan-91** [comment]
I can confirm this using an AMD RX 580 and Mesa drivers. This happens in the Linux version and also the Windows version running in Wine. Not sure if the Wine log will be helpful, but I've attached both. Unfortunately this black squares bug makes the game nearly unplayable with OpenGL. Yuzu crashes when trying to use Vulkan so that's not an open for me (hence no Vulkan logs to provide).

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5685478/yuzu_log.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5685490/yuzu_log.txt)

**Comment by titan-91** [comment]
Playing more through the game, two tracks do not exhibit this bug very much. Coco Park very little, and Papu's Pyramid not at all. It only seems to happen in tunnels and caves with certain types of shadows. The pixels follow the caves loosely as you drive.

**Comment by hunterOO1** [comment]
Same here.
CPU: Ryzen 5 1600x
GPU: RX 580

The glitches happens in VULKAN and OPENGL... Dont matter what I chose.

**Comment by C1fer** [comment]
The issue seems to have been fixed with bcr. The dither-like pattern in the first track is still there, though

**Comment by titan-91** [comment]
It's not fixed unfortunately, at least not for AMD card users like myself. The squares are still there in the latest automatic Windows and Linux builds. Happens with OpenGL and Vulkan.
