### ISSUE TITLE
TCR Regression - SM3DAS Intro Video Frame Not Fully Displayed

### ISSUE THREAD

**Issue by ameerj** [yuzu-emu/yuzu#5329]
After the TCR merge in Mainline 491, there has been a regression with the SM3DAS intro video causing the bottom ~10% of the video frame to no longer be displayed. 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5793587/yuzu_log.txt)

![side_by_side](https://user-images.githubusercontent.com/52414509/104139499-ed297f00-5379-11eb-8d0d-ed03b0b7edb3.PNG)

https://user-images.githubusercontent.com/52414509/104139503-f3b7f680-5379-11eb-9ea8-e36cfef97e2e.mp4

https://user-images.githubusercontent.com/52414509/104139508-f74b7d80-5379-11eb-909c-1102b0946737.mp4

**Comment by gidoly** [comment]
seems fixed here

https://user-images.githubusercontent.com/66776795/205191515-54058684-5c42-4e97-b823-9c5cc3b6d2c8.mp4

can you test when you have time?

**Comment by gidoly** [comment]
fixed feel free to reopen if still happens

**Comment by ameerj** [comment]
Still happens.

https://user-images.githubusercontent.com/52414509/212807712-ab6ded20-713c-4eba-bd74-087c3f90b131.mp4
