### ISSUE TITLE
Significant Audio Lag in Xenoblade Chronicles 2

### ISSUE THREAD

**Issue by Ni-Ma** [yuzu-emu/yuzu#5988]
I am using yuzu mainline 636-4756-gfa512bb1f.

In all cutscenes in Xenoblade Chronicles 2, the audio lags behind the visuals by approximately 1-2 seconds. This is readily apparent on the opening cinematic. I tested this in Ryujinx as well, and the audio synced well, but the rendering and framerates were worse than Yuzu. All updates and DLC are disabled.

My system is:
Ryzen 3700x
RTX 2060
32 GB ram
NVMe SSD

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6029500/yuzu_log.txt)

**Comment by german77** [comment]
Fixed by #6498

**Comment by RenanTafner** [comment]
I can confirm this issue is still happening in the latest official release and latest early access (2908), the audio gets out of sync of visuals (audio coming late) in all cinematics and some cutscenes by about 1 second
