### ISSUE TITLE
Super Mario Maker 2 - Audio speeds up randomly while gameplay is normal speed

### ISSUE THREAD

**Issue by lightgod87** [yuzu-emu/yuzu#6027]
Good day,

The motive for this issue is about an issue with the audio core. I saw this happening in Crash Team Racing: Nitro-Fueled, and in this ticket, Super Mario Maker 2.

It just so happens that, I dunno why, the in-game audio all of a sudden (and randomly) doubles the speed, while the gameplay speed keeps being the same. These are the specs:

Yuzu Version: EA 1492
CPU: AMD Ryzen 5 5600X
GPU: Nvidia Geforce RTX 3060 Ti
GPU Driver Version: 461.72
RAM: 32 GBs DDR4
OS: Windows 10

I'll attach the log.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6072385/yuzu_log.txt)

**Comment by lightgod87** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6094539/yuzu_log.txt)

Alright, same issue in CTR: NF. I was able to replicate this again. I attach the new log.

**Comment by nikpmr** [comment]
Same problem here with Crash Team Racing. Sound will speed up 2x during gameplay, and sometimes even faster later on. Gameplay is unaffected. Ryzen 5 2600, RTX 2060.

Tried both OpenGL and Vulcan. 60FPS mod seemed to solve the issue, but then it reappeared after starting a race.

**Comment by jhol** [comment]
I noticed this in Breath of the Wild also

**Comment by JOHN30011887** [comment]
Also have it with Crash Team Racing, i usually get the speed up audio issue but sometimes i get the slow distorted audio

**Comment by benderscruffy** [comment]
has this been fixed in #8545

**Comment by BParks21** [comment]
Still broken, at first I thought it was related to the 60fps mod but the issue persists without the mod.

**Comment by DmitriiShamrikov** [comment]
I have the same issue with Bayonetta 3, except it's not random but all the time
