### ISSUE TITLE
video_core: Many particle effects are static

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#6091]
Caused by #5741 

So far observed in BOTW (remote bomb, lightning), ZLA (bombs), and Splatoon 2 (entering levels in Octo Canyon, spawning). A bit difficult to explain in English, but when an explosion emits a large number of particles outward, those particles don't move outward and may flicker.

https://user-images.githubusercontent.com/22451773/111859615-15b19480-893a-11eb-99c7-61e9cba7b4cf.mp4

https://user-images.githubusercontent.com/22451773/111859620-19ddb200-893a-11eb-9bc7-0a65eab27c20.mp4

https://user-images.githubusercontent.com/22451773/111860597-8bb8fa00-8940-11eb-9b80-0ae225d55b4e.mp4

I had to exit back to Octo Canyon and re-enter the level to observe the issue in Splatoon 2.

Log of Splatoon 2: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6174940/yuzu_log.txt)

EDIT: More issues have been brought to attention that can be rolled into this issue.

BOTW: In fact, most particle effects are broken.

https://user-images.githubusercontent.com/22451773/111863217-12c29e00-8952-11eb-9204-c3366b84b566.mp4

https://user-images.githubusercontent.com/22451773/111863218-135b3480-8952-11eb-8b87-1a1ec6aea11e.mp4

ACNH: Chimney smoke is buggy and occasionally stops moving. This is difficult to record: my screen capture options for some reason causes the smoke to start working correctly. Due to this variability, it is potentially a separate issue. You can see it at the beginning of this video.

https://user-images.githubusercontent.com/22451773/111863855-cda06b00-8955-11eb-9710-25829997fd64.mp4

Also on ACNH, it was reported that snowflakes floating in the wind are buggy, but I was unable to reproduce this.

Edit 2021-03-25: ACNH rain is broken

https://user-images.githubusercontent.com/22451773/112544685-3b61f200-8daf-11eb-8723-98dbc50c1101.mp4

Edit 2021-04-08: Pokemon Sword precipitation

https://user-images.githubusercontent.com/22451773/113969756-1183e300-9825-11eb-81f5-e6d5d5f285cf.mp4

**Comment by AntoSkate** [comment]
In Splatoon 2 the launchpads, scrolls and sardinium particles are also broken



https://user-images.githubusercontent.com/36473846/113013144-be05fb00-917b-11eb-8059-e949bccb7add.mp4


https://user-images.githubusercontent.com/36473846/113013168-c2caaf00-917b-11eb-9c03-d4fc5afe0aef.mp4


https://user-images.githubusercontent.com/36473846/113013154-bfcfbe80-917b-11eb-8592-4c710125cede.mp4

**Comment by v1993** [comment]
This also appears to be an issue in Kirby Star Allies, most noticeable on volcano levels, with burning particles flying upwards in jittery manner. Confetti also seems to be affected the same way.

**Comment by AntoSkate** [comment]
I found something interesting: with the multicore cpu emulation off all the particles works well in splatoon 2 and breath of the wild, i'll test with other games later

**Comment by FernandoS27** [comment]
This is actuallly a regression of BCR and is a bug on High Accuracy setting which is suppose to fix this issue.

**Comment by v1993** [comment]
Can someone retest this, please? The issue from Kirby Star Allies I've reported earlier is fixed now.

**Comment by gidoly** [comment]
currentlky high accuracy fixes issue but pokemon one seems can still happen depands on scene

**Comment by gidoly** [comment]
should fixed on last ea and mainline on both normal and high
