### ISSUE TITLE
LAYTON’S MYSTERY JOURNEY not fully working yet

### ISSUE THREAD

**Issue by DocMAX** [yuzu-emu/yuzu#6352]
Used build:
![grafik](https://user-images.githubusercontent.com/5351323/119272939-d721aa00-bc08-11eb-9e78-bacf146c2506.png)

Game with problems:
![grafik](https://user-images.githubusercontent.com/5351323/119272949-e86ab680-bc08-11eb-95be-bbe4ad26cf6f.png)

Problem:
In Vulkan screen is up-side-down and flipped. In Vulkan and OpenGL: Ingame-Layer only shows black screen. (Other layers (menu, subtitles.. work)
![grafik](https://user-images.githubusercontent.com/5351323/119273154-d63d4800-bc09-11eb-84ff-23281dc0563d.png)

Specs:
AMD Ryzen 9 5950X 16-Core Processor
Nvidia RTX 3080 driver 465.31
Linux Gentoo Kernel 5.12.6

Log: attached
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6528738/yuzu_log.txt)

**Comment by Krako13** [comment]
Same here on windows with i5 7600 - nvidia 1060 (6go).

**Comment by JeonDohyeon** [comment]
Same issue in #2703: flips in Vulkan and not showing up in OpenGL.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6759208/yuzu_log.txt)
Both tested in Vulkan & OpenGL.
Vulkan..
![image](https://user-images.githubusercontent.com/34373595/124369687-91490e80-dca9-11eb-8804-badcd5a19d85.png)
OpenGL..
![image](https://user-images.githubusercontent.com/34373595/124369688-9443ff00-dca9-11eb-9dbb-b21993df8cd0.png)

**Comment by DocMAX** [comment]
At some point the flipped screen has been fixed, but still black screen in the intro movie.

**Comment by PAULg013** [comment]
> Same issue in #2703: flips in Vulkan and not showing up in OpenGL. [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6759208/yuzu_log.txt) Both tested in Vulkan & OpenGL. Vulkan.. ![image](https://user-images.githubusercontent.com/34373595/124369687-91490e80-dca9-11eb-8804-badcd5a19d85.png) OpenGL.. ![image](https://user-images.githubusercontent.com/34373595/124369688-9443ff00-dca9-11eb-9dbb-b21993df8cd0.png)

Have you fixed OpenGL Broken OpenGL screen ?
I can run the game with OpenGL but can only see the half of the screen

**Comment by JeonDohyeon** [comment]
> > Same issue in #2703: flips in Vulkan and not showing up in OpenGL. [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6759208/yuzu_log.txt) Both tested in Vulkan & OpenGL. Vulkan.. ![image](https://user-images.githubusercontent.com/34373595/124369687-91490e80-dca9-11eb-8804-badcd5a19d85.png) OpenGL.. ![image](https://user-images.githubusercontent.com/34373595/124369688-9443ff00-dca9-11eb-9dbb-b21993df8cd0.png)
> 
> Have you fixed OpenGL Broken OpenGL screen ? I can run the game with OpenGL but can only see the half of the screen

I've been not using yuzu for months so I'm not sure it properly work now. With OpenGL it'll be fixed at some point but as far I know it's still not fixed in Vulkan, which is relatively hyper-speed compared with OpenGL.

**Comment by DocMAX** [comment]
Works flawlessly with Ryujinx now!!!

**Comment by gidoly** [comment]
issue mentioned is fixed on yuzu however it still has issue on if you start new game. i made seperate issue thread for that. so i'll close this for now
