### ISSUE TITLE
Pikmin 3 Multiplayer Crash

### ISSUE THREAD

**Issue by Nurukhi** [yuzu-emu/yuzu#7281]
I've tested this issue in numerous builds for some months now, it's happened in every one of them, although I'm playing in the mainline build, the latest right now, the 777. The thing is, the game crashes ALWAYS when you are in co-op mode, in day two, in the first cinematic with Brittany or when you get a fruit to the ship. I'd like for this to be fixed because I'd love to play this game in co-op with Parsec. Thanks in advance!

**Comment by G-Spawn** [comment]
for posterity sake, could you provide a log at earliest convenience?

**Comment by Nurukhi** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7471141/yuzu_log.txt)
There ^^

**Comment by michaelschulte2k** [comment]
ive been getting the crash in two player mode in side stories, I cant proceed to day 2 after completing day 1

**Comment by Demidjack13** [comment]
the way i fixed it crashing after enabling coop mode was setting the resolution lower. first i had it on 4k it crashed then i lowered it to 2k and it seemed to work after

**Comment by giodude12** [comment]
I would like to add to this issue that this still happens to me on Yuzu 3745 at 2K res
