### ISSUE TITLE
BOTW no longer playable at 60fps since scaling release

### ISSUE THREAD

**Issue by Infinality** [yuzu-emu/yuzu#7414]
BOTW was largely playable at 60fps for my setup, prior to the recent release of the new scaling feature (a week or so ago).  Since then, the most I can seem to get is 38 fps.  I've tried changing scaling factors (even .5x), rendering backends, buffering settings in nvidia and just about every other setting I could think of.  All other games seem to work better since that release, except for BOTW.

Running with Vulkan with 2x / bilinear / FXAA on Windows 10 with Nvidia RTX 2060.

**Comment by G-Spawn** [comment]
Can help if you provide a log as well.

**Comment by FernandoS27** [comment]
hmn, 1x shouldn't be affected though.

**Comment by Infinality** [comment]
I guess I can't say for absolute sure that the scaling is what is causing it.  It's possible that something else changed right around then too unrelated to scaling.

**Comment by FernandoS27** [comment]
just check in x1.

**Comment by Infinality** [comment]
> just check in x1.

I did.  Still about 38 fps.  The scaling factor doesn't seem to matter.  Even if I change to .5, 1, or 2, it's around 38 fps.

**Comment by FernandoS27** [comment]
this seems wrong, I'll need you to get to the version of the regression: https://github.com/yuzu-emu/yuzu-mainline/releases and compare 2 microprofiles of BotW.

To use the microprofile, on yuzu's window go to View -> Debugging -> Microprofile.

you'll activate "Timers -> Exclusive Timers" and on groups "Groups -> GPU + Vulkan (or OGL)". I'll need screenshots of both versions (pre regression, post regression).

Also which graphics backend do you use?. If it's OGL, we are forcing GLASM until Nvidia fixes their driver. Vulkan is even better for BotW

**Comment by Infinality** [comment]
Using Vulkan.  Here's from 823.  Might take me a bit to find the release where it worked.

![image](https://user-images.githubusercontent.com/1253650/142952594-78baf3f7-349e-4c7c-9583-5947cfb4da5a.png)

**Comment by Infinality** [comment]
So, I've gone back to 799, and the issue is still present there at 60 fps.  I can only assume something else changed, perhaps on my system, that is causing this.  I know I've updated my nvidia driver to 496.76, about a week ago, so perhaps that was the cause and not yuzu?

**Comment by FernandoS27** [comment]
hmn,

https://developer.nvidia.com/vulkan-driver
scroll down to "Vulkan Beta Driver Downloads"
and install the windows driver. Let me know how it goes.

**Comment by Infinality** [comment]
So, this is interesting.  I updated to the beta Vulkan driver and rebooted.  The framerate in BOTW is *lower* than before, just around 33 fps.  BUT, other games I've used when checking FPS like Odyssey, Link's Awakening, and Bowser's Fury run better than before.  They were already mostly 60 fps but would occasionally jitter when rotating the camera.  With the beta driver, they are perfectly smooth (after the initial loading jitters).

**Comment by FernandoS27** [comment]
I think it's best that you put a log so i see what could be wrong in it.

**Comment by Infinality** [comment]
Attached the sanitized log file.  Thanks for checking into this.  I've been playing BOTW on cemu, so this isn't really holding me up, but I just wanted to report it in case there was a regression in yuzu.

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7585362/yuzu_log.zip)

**Comment by FernandoS27** [comment]
@Infinality is this still happening?

**Comment by Infinality** [comment]
Yes, unfortunately.  I tested it with 828 this morning after Link's Awakening was fixed, but it's still happening here.

**Comment by FernandoS27** [comment]
> Yes, unfortunately. I tested it with 828 this morning after Link's Awakening was fixed, but it's still happening here.

Could you get me both microprofiles? of the version that worked and the 828 ?

**Comment by Infinality** [comment]
I wasn't able to locate a previous release that worked properly, so I think there must have been something else that changed on my system that I don't know.  If there's nothing actionable you can do at this point, then I suppose it can just be closed.

**Comment by german77** [comment]
This should be fixed now. Reopen if necessary

**Comment by Infinality** [comment]
I'm still getting low 30s FPS.  I'll chalk it up to something on my system, and I've been playing this on CEMU anyway, but wanted to report it.

**Comment by Infinality** [comment]
For whatever it's worth, sometime in the past week or so, with a recent update, I'm now getting up to 48 fps, so definitely a huge improvement.
