### ISSUE TITLE
Language Selection problem on Super Mario 3D Allstars (Mario Sunshine)

### ISSUE THREAD

**Issue by Djipi71** [yuzu-emu/yuzu#8210]
Yuzu EA 2678
Game version : 1.0.0

Issue:
When you are on the select game screen , you can change te languages of the games. Select mario sunshine and french language for exemple, and start the game. The game stay in english.
I have test Super mario 64 and Super Mario Galaxy , and this 2 others games are in french. So the problem is only for Super Mario Sunshine.

Log: For the test , i have select French language for Super Mario Sunshine

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8495473/yuzu_log.txt)

**Comment by MegaMimh** [comment]
Have you found a solution? I have the same problem. Thx

**Comment by MegaMimh** [comment]
Yuzu 1124 and ER 2890 and others..
Game version : 1.0.1

I pushed the tests further we can select any language (tested with French, Deutch, Spanish, Italian) Super Mario Sunshine launches only in English on Yuzu .
Let's hope that a fix will come..

**Comment by MegaMimh** [comment]
Hello,

To date, the problem is still not fixed.
Is there any chance to see this little problem solved please?

Thanks to you, have a nice day.

**Comment by 1stupid23** [comment]
does the problem still exist, have you been able to solve it?

**Comment by Djipi71** [comment]
Yes test on the last EA and master and the problem language still here :(

**Comment by FearlessTobi** [comment]
Not an fs issue.
