### ISSUE TITLE
Super Mario 3D All-Stars

### ISSUE THREAD

**Issue by jvhellraiser** [yuzu-emu/yuzu#8216]
Many issues encounter with Super Mario 3D All-Stars Mario64 black screen, and Mario missing body
,missing covers etc, not sure what it is and i am not good with reporting this things i believe pictures are better at talking for me..

![Screenshot 2022-04-15 205637](https://user-images.githubusercontent.com/16488761/163655792-3b0ad8cc-9680-4bca-9b5a-325898881639.png)
![Screenshot 2022-04-15 205808](https://user-images.githubusercontent.com/16488761/163655794-84b8b725-1219-4221-89fc-f3d91bfc6cd0.png)
![Screenshot 2022-04-15 205836](https://user-images.githubusercontent.com/16488761/163655795-6b4f6314-43ae-43d6-8ad9-2c8da58b6c55.png)
![Screenshot 2022-04-15 205901](https://user-images.githubusercontent.com/16488761/163655796-3ee4c025-7732-4751-9aa1-40de8ea53ad7.png)
![Screenshot 2022-04-15 205947](https://user-images.githubusercontent.com/16488761/163655798-afbf8964-5836-4182-8ef7-392f2e32baaf.png)

I7 9700k 16 gb ram Nvidia RTX 2080
Build EA 2680, all configuration are at Default
no configuration have bee change...

**Comment by BSoDGamingYT** [comment]
Use the GLSL shader backend, instead of GLASM

**Comment by jvhellraiser** [comment]
> Use the GLSL shader backend, instead of GLASM

Yeah this is what i thought but it still the same with GLSL
![Screenshot 2022-04-15 213726](https://user-images.githubusercontent.com/16488761/163656896-fc5e0ec9-27b0-4b24-b56c-663f5608590c.png)
![Screenshot 2022-04-15 213631](https://user-images.githubusercontent.com/16488761/163656901-70eac5f6-76ef-472c-b7d2-3dd32a128c89.png)

**Comment by gidoly** [comment]
Post the log

**Comment by jvhellraiser** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8499091/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/8499092/yuzu_log.txt.old.txt)

i hope these are the logs...

**Comment by gidoly** [comment]
try clean install gpu driver after delete driver with display driver uninstaller
https://www.wagnardsoft.com/DDU/download/DDU%20v18.0.4.9.exe
i saw similar issue report on discord it solved by driver clean install might worth to give a try

**Comment by jvhellraiser** [comment]
> try clean install gpu driver after delete driver with display driver uninstaller https://www.wagnardsoft.com/DDU/download/DDU%20v18.0.4.9.exe i saw similar issue report on discord it solved by driver clean install might worth to give a try

I already try a clean install of the Nvidia Drivers same day the error started showing....that did not fix it..

**Comment by liamwhite** [comment]
It looks like you are using GLSL in the game-specific settings. This does not work for the 3D All-Stars bundle due to the way it launches subprograms. Use GLSL in your global settings, or play with Vulkan instead.

**Comment by jvhellraiser** [comment]
> It looks like you are using GLSL in the game-specific settings. This does not work for the 3D All-Stars bundle due to the way it launches subprograms. Use GLSL in your global settings, or play with Vulkan instead.

Nice of you to mention this, didn't know this game was affected by the game-specific settings,
That's interesting i still get  a bit of trash in the intro when using Vulkan / GLSL does not seems to work for me.

**Comment by gidoly** [comment]
issue still persist?

**Comment by gidoly** [comment]
close due to no response and can't reproduce on developers and testers hardware
