### ISSUE TITLE
The latest yuzu can't run Ring Fit Adventure. 

### ISSUE THREAD

**Issue by zhengwz** [yuzu-emu/yuzu#8253]
The latest yuzu can't run Ring Fit Adventure. It's always booting.

**Comment by Still34** [comment]
Same here. Here's a more comprehensive report info.

Title ID: 01002FF008C24000 (Ring Fit Adventure)
- XCI MD5: ED923D3547AE6062A92C13978FE97FE9
- XCI dumped via nxdumptool rewrite branch b8992d1 (Atmosphere 1.3.1; firmware 14.1.1)
- NSPs (updates & DLCs) dumped via nxdumptool stable 1.1.15
Version: yuzu 996 (https://github.com/yuzu-emu/yuzu-mainline/commit/175153303b2be99d09dfd23884113d318657c577)

Log
```
[   8.576108] Frontend <Info> yuzu\main.cpp:BootGame:1391: yuzu starting...
[   8.578627] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   8.594169] Config <Info> common\settings.cpp:LogSettings:40: yuzu Configuration:
[   8.594175] Config <Info> common\settings.cpp:operator ():33: Controls_UseDockedMode: true
[   8.594176] Config <Info> common\settings.cpp:operator ():33: System_RngSeed: 0
[   8.594176] Config <Info> common\settings.cpp:operator ():33: System_CurrentUser: 0
[   8.594177] Config <Info> common\settings.cpp:operator ():33: System_LanguageIndex: 16
[   8.594177] Config <Info> common\settings.cpp:operator ():33: System_RegionIndex: 6
[   8.594178] Config <Info> common\settings.cpp:operator ():33: System_TimeZoneIndex: 0
[   8.594178] Config <Info> common\settings.cpp:operator ():33: Core_UseMultiCore: true
[   8.594183] Config <Info> common\settings.cpp:operator ():33: CPU_Accuracy: 0
[   8.594185] Config <Info> common\settings.cpp:operator ():33: Renderer_UseResolutionScaling: 3
[   8.594185] Config <Info> common\settings.cpp:operator ():33: Renderer_ScalingFilter: 5
[   8.594186] Config <Info> common\settings.cpp:operator ():33: Renderer_AntiAliasing: 1
[   8.594187] Config <Info> common\settings.cpp:operator ():33: Renderer_UseSpeedLimit: false
[   8.594187] Config <Info> common\settings.cpp:operator ():33: Renderer_SpeedLimit: 100
[   8.594188] Config <Info> common\settings.cpp:operator ():33: Renderer_UseDiskShaderCache: true
[   8.594189] Config <Info> common\settings.cpp:operator ():33: Renderer_GPUAccuracyLevel: 1
[   8.594190] Config <Info> common\settings.cpp:operator ():33: Renderer_UseAsynchronousGpuEmulation: true
[   8.594190] Config <Info> common\settings.cpp:operator ():33: Renderer_NvdecEmulation: 2
[   8.594191] Config <Info> common\settings.cpp:operator ():33: Renderer_AccelerateASTC: true
[   8.594191] Config <Info> common\settings.cpp:operator ():33: Renderer_UseVsync: false
[   8.594192] Config <Info> common\settings.cpp:operator ():33: Renderer_ShaderBackend: 1
[   8.594192] Config <Info> common\settings.cpp:operator ():33: Renderer_UseAsynchronousShaders: true
[   8.594193] Config <Info> common\settings.cpp:operator ():33: Renderer_AnisotropicFilteringLevel: 5
[   8.594193] Config <Info> common\settings.cpp:operator ():33: Audio_OutputEngine: auto
[   8.594194] Config <Info> common\settings.cpp:operator ():33: Audio_OutputDevice: auto
[   8.594194] Config <Info> common\settings.cpp:operator ():33: DataStorage_UseVirtualSd: true
[   8.594195] Config <Info> common\settings.cpp:operator ():37: DataStorage_CacheDir: C:\Users\Still\AppData\Roaming\yuzu\cache
[   8.594196] Config <Info> common\settings.cpp:operator ():37: DataStorage_ConfigDir: C:\Users\Still\AppData\Roaming\yuzu\config
[   8.594197] Config <Info> common\settings.cpp:operator ():37: DataStorage_LoadDir: C:\Users\Still\AppData\Roaming/yuzu/load/
[   8.594198] Config <Info> common\settings.cpp:operator ():37: DataStorage_NANDDir: C:\Users\Still\AppData\Roaming\yuzu\nand
[   8.594198] Config <Info> common\settings.cpp:operator ():37: DataStorage_SDMCDir: C:\Users\Still\AppData\Roaming/yuzu/sdmc/
[   8.594199] Config <Info> common\settings.cpp:operator ():33: Debugging_ProgramArgs: 
[   8.594199] Config <Info> common\settings.cpp:operator ():33: Input_EnableMotion: true
[   8.594200] Config <Info> common\settings.cpp:operator ():33: Input_EnableVibration: true
[   8.594200] Config <Info> common\settings.cpp:operator ():33: Input_EnableRawInput: false
[   8.665463] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   8.789134] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:Device:418: Device doesn't support float16 natively
[   9.014063] Render.Vulkan <Warning> video_core\vulkan_common\vulkan_device.cpp:Device:631: Blacklisting Volta and older from VK_KHR_push_descriptor
[   9.014070] Render.Vulkan <Warning> video_core\vulkan_common\vulkan_device.cpp:Device:637: NVIDIA Drivers >= 510 do not support MSAA image blits
[   9.150160] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:179: Driver: NVIDIA 512.20.0.0
[   9.150169] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:180: Device: NVIDIA GeForce GTX 1070
[   9.150170] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:181: Vulkan: 1.3.194
[   9.318343] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:128: Patching ExeFS for title_id=01002FF008C24000
[   9.319146] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:144:     ExeFS: Update (v0.5.0) applied successfully
[   9.319492] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:175:     ExeFS: LayeredExeFS patches applied successfully
[   9.519635] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=31A2773EA6928FFE3D32B17B3AD08F54826DA39F
[   9.639473] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=B0A94A27A8EA158CF81FC9B83E9366E6
[   9.677228] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=7040311F0662E3519CF01FDACA3641128CE4F305
[   9.724934] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=230994ACC1EB0F13878DD155361BEFF36EDD1B43
[   9.813613] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   9.813987] Frontend <Info> yuzu\main.cpp:BootGame:1492: Booting game: 01002FF008C24000 | Ring Fit Adventure (64-bit) | 1.2.0
[   9.814332] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:LoadDiskResources:448: Total Pipeline Count: 0
[  10.020578] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  10.027604] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  10.036039] Service.AM <Warning> core\hle\service\am\am.cpp:GetGpuErrorDetectedSystemEvent:1750: (STUBBED) called
[  10.042210] Service.AM <Warning> core\hle\service\am\am.cpp:GetCurrentFocusState:746: (STUBBED) called
[  10.042938] Service.AM <Warning> core\hle\service\am\am.cpp:AcquireForegroundRights:93: (STUBBED) called
[  10.043626] Service.AM <Warning> core\hle\service\am\am.cpp:SetFocusHandlingMode:432: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[  10.044147] Service.AM <Warning> core\hle\service\am\am.cpp:SetOutOfFocusSuspendingEnabled:451: (STUBBED) called enabled=false
[  10.046011] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  10.048112] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  10.050917] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  10.051157] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  10.051801] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[  13.045378] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  13.052474] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:421: Patching RomFS for title_id=01002FF008C24000, type=01
[  13.053327] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[  13.059085] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:421: Patching RomFS for title_id=01002FF008C24000, type=01
[  13.059688] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[  13.073565] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:Initialize:155: (STUBBED) called
[  13.076165] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:SetAruid:200: (STUBBED) called, pid=0x51
[  13.077031] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:SetGraphicsFirmwareMemoryMarginEnabled:208: (STUBBED) called
[  13.080629] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetManagerDisplayService:458: (STUBBED) called
[  13.081297] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetSystemDisplayService:450: (STUBBED) called
[  13.081785] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetRelayService:442: (STUBBED) called
[  13.086723] Service.VI <Warning> core\hle\service\vi\vi.cpp:OpenDisplay:474: (STUBBED) called
[  13.088012] Service.AM <Warning> core\hle\service\am\am.cpp:CreateManagedDisplayLayer:465: (STUBBED) called
[  13.092945] Service.VI <Warning> core\hle\service\vi\vi.cpp:AdjustRefcount:113: (STUBBED) called id=1, addval=00000001, type=00000000
[  13.093520] Service.VI <Warning> core\hle\service\vi\vi.cpp:AdjustRefcount:113: (STUBBED) called id=1, addval=00000001, type=00000001
[  13.096575] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetNativeHandle:124: (STUBBED) called id=1, unknown=0000000F
[  13.099012] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetDisplayVsyncEvent:678: (STUBBED) called. display_id=0x0000000000000000
[  13.125689] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  13.141231] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:QueryEvent:168: (STUBBED) called, fd=1, event_id=2
[  13.143565] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_as_gpu.cpp:AllocAsEx:85: (STUBBED) called, big_page_size=0x10000
[  13.143883] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_as_gpu.cpp:GetVARegions:281: (STUBBED) called, buf_addr=0, buf_size=0
[  13.144546] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_as_gpu.cpp:GetVARegions:309: (STUBBED) called, buf_addr=0, buf_size=30
[  13.156589] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.158811] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.161949] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.193647] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.194106] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.199898] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_as_gpu.cpp:BindChannel:270: (STUBBED) called, fd=4
[  13.200541] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:AllocGPFIFOEx2:168: (STUBBED) called, num_entries=10000, flags=1, unk0=0, unk1=0, unk2=0, unk3=0
[  13.200828] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:AllocateObjectContext:182: (STUBBED) called, class_num=B197, flags=0
[  13.201054] Service.NVDRV <Info> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:ChannelSetTimeout:316: called, timeout=0x266
[  13.201600] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:QueryEvent:168: (STUBBED) called, fd=4, event_id=3
[  13.201911] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:SetErrorNotifier:148: (STUBBED) called, offset=0, size=1000, mem=4
[  13.203260] Service.NVDRV <Info> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:ChannelSetTimeslice:324: called, timeslice=0x400
[  13.203893] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.204362] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.207135] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.207554] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.224038] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  13.226057] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.226065] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.226066] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.226067] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.226068] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.226069] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.231956] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.232527] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.238265] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238272] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238273] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238273] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238274] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238275] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238278] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238281] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238282] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238283] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238293] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238294] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238294] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238295] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238296] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238297] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238298] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238298] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238299] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238300] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238301] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238302] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.238302] HW.GPU <Warning> video_core\engines\maxwell_3d.cpp:ProcessFirmwareCall4:440: (STUBBED) called
[  13.239875] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  13.247473] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocGetId:148: called
[  13.253985] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocGetId:148: called
[  13.254134] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocGetId:148: called
[  13.261215] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.261684] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.262714] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.263171] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.270010] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  13.281809] Service.APM <Info> core\hle\service\apm\apm_controller.cpp:SetClockSpeed:83: called, mhz=000006F9
[  13.298976] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  13.310511] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[  13.314197] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[  13.317953] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  13.330013] Service.AM <Warning> core\hle\service\am\am.cpp:SetOperationModeChangedNotification:403: (STUBBED) called flag=true
[  13.330190] Service.AM <Warning> core\hle\service\am\am.cpp:SetPerformanceModeChangedNotification:413: (STUBBED) called flag=true
[  13.330385] Service.AM <Warning> core\hle\service\am\am.cpp:SetRestartMessageEnabled:439: (STUBBED) called
[  13.358099] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[  13.358709] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[  13.414174] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  13.414776] Service.ACC <Warning> core\hle\service\acc\acc.cpp:InitializeApplicationInfoRestricted:740: (Partial implementation) called
[  13.414798] Service.ACC <Warning> core\hle\service\acc\acc.cpp:InitializeApplicationInfoBase:783: ApplicationInfo init required
[  13.423301] Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:878: called.
[  13.424174] Debug <Critical> core\hle\service\filesystem\fsp_srv.cpp:operator ():902: Unreachable code!
[  13.581485] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.589274] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.589762] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.631687] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.632858] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.633314] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.634318] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.634758] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.640065] Service.APM <Info> core\hle\service\apm\apm_controller.cpp:SetClockSpeed:83: called, mhz=000003FC
[  13.640581] Service.APM <Info> core\hle\service\apm\apm_controller.cpp:SetClockSpeed:83: called, mhz=000003FC
[  13.729858] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.730287] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.734916] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.735390] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.736240] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.736682] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.738852] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:244: (STUBBED) called
[  13.738859] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:252: Avoiding passing null pointer to memcpy
[  13.741644] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.742072] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.761461] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.761978] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.763343] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.763843] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.794775] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.795314] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.814665] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.815192] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.825562] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.826096] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.839426] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.839943] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.856380] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.857054] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.877380] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.885596] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.887139] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.901801] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.904018] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.904843] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.907281] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.933288] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.980688] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.982159] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.982769] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.983355] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.983995] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.984585] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.985170] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.994612] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  13.995143] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.003979] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.004532] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.008639] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.009150] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.015936] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.016438] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.017104] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.017613] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.019073] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.019609] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.020243] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.020913] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.021495] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.021989] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.022614] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.023127] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.039983] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.119346] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:QuerySystemEvent:126: (STUBBED) called
[  14.124765] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:Start:108: (STUBBED) called
[  14.139440] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  14.155543] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  14.155955] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioTvOutput, volume=1
[  14.156541] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  14.156593] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioBuiltInSpeakerOutput, volume=2
[  14.156922] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  14.156961] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioUsbDeviceOutput, volume=2
[  14.157229] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  14.157255] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioStereoJackOutput, volume=2
[  14.158322] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:GetActiveChannelCount:289: (STUBBED) called
[  14.158986] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  14.159324] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:GetActiveAudioDeviceName:264: (STUBBED) called
[  14.287876] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  14.287925] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioTvOutput, volume=1
[  14.288323] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  14.288360] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioBuiltInSpeakerOutput, volume=1
[  14.288744] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  14.288792] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioUsbDeviceOutput, volume=1
[  14.289008] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[  14.289040] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioStereoJackOutput, volume=1
[  14.857647] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.858205] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.965720] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  14.966271] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  15.010337] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  15.017740] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  15.020162] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  15.020695] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  15.022240] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  15.022778] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  15.027666] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  15.028199] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  15.029653] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  15.030162] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  15.086902] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[  19.910413] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  19.914453] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  19.914990] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  19.917402] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  19.917930] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  19.937488] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  19.938016] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  20.034644] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  20.035612] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  20.036168] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  20.037165] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  20.037711] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:201: (STUBBED) called type=1
[  20.042658] Service.AM <Warning> core\hle\service\am\am.cpp:SetFocusHandlingMode:432: (STUBBED) called. unknown0=1, unknown1=0, unknown2=1
[  20.042703] Service.AM <Warning> core\hle\service\am\am.cpp:SetOutOfFocusSuspendingEnabled:451: (STUBBED) called enabled=false
[  20.348595] Service.HID <Error> core\hid\emulated_controller.cpp:SetSupportedNpadStyleTag:944: Controller type 3 is not supported. Disconnecting controller
[  20.349962] Service.HID <Info> core\hle\service\hid\hid.cpp:SetNpadJoyAssignmentModeSingle:1066: called, npad_id=0, applet_resource_user_id=81, npad_joy_device_type=1
[  20.351438] Service.HID <Error> core\hle\service\hid\controllers\npad.cpp:SetGyroscopeZeroDriftMode:1043: Invalid Npad type 0
[  20.362515] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1508: (STUBBED) called, result=0x0000C8CA
[  20.362660] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:571: Signalling debugger, PANIC! info1=0x000000107D800A48, info2=0x0000000000000004
[  20.362666] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:operator ():552: debug_buffer_err_code=C8CA
[  20.362674] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:622: Emulated program broke execution! reason=0x0000000000000000, info1=0x000000107D800A48, info2=0x0000000000000004
[  20.362675] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:79: Backtrace, sp=000000107D800890, pc=000000000AC0B4D4
[  20.362678] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:81: Module Name         Address             Original Address    Offset              Symbol
[  20.362678] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:82: 
[  20.444001] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100056518    000000000AB65518    0000000000056518    _ZN2nn4diag6detail5AbortEPKNS_6ResultE
[  20.444010] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100054E0C    000000000AB63E0C    0000000000054E0C    _ZN2nn4diag6detail10VAbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoES3_St9__va_list
[  20.444012] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100054ED4    000000000AB63ED4    0000000000054ED4    _ZN2nn4diag6detail9AbortImplEPKcS3_S3_iPKNS_6ResultES3_z
[  20.444013] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 00000071003598F8    000000000AE688F8    00000000003598F8    _ZN2nn3hid25SetGyroscopeZeroDriftModeERKNS0_19SixAxisSensorHandleERKNS0_22GyroscopeZeroDriftModeE
[  20.444014] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                00000071000F75DC    00000000080FB5DC    00000000000F75DC    
[  20.444015] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                00000071000FE424    0000000008102424    00000000000FE424    
[  20.444017] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                0000007100854CF0    0000000008858CF0    0000000000854CF0    
[  20.444019] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                0000007101260284    0000000009264284    0000000001260284    
[  20.444020] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                00000071012639D4    00000000092679D4    00000000012639D4    
[  20.444020] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                0000007100F11EF4    0000000008F15EF4    0000000000F11EF4    
[  20.444021] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                0000007100F360DC    0000000008F3A0DC    0000000000F360DC    
[  20.444022] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                0000007100F353D4    0000000008F393D4    0000000000F353D4    
[  20.444023] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 00000071000CFB44    000000000ABDEB44    00000000000CFB44    
[  20.444023] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 00000071000D4310    000000000ABE3310    00000000000D4310    
[  20.444024] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 00000070F54F0FFC    FFFFFFFFFFFFFFFC    FFFFFFFFF54F0FFC    
```

**Comment by cybik** [comment]
Confirming here. Neither 1.0.0 nor 1.2.0 will start with the latest available mainline build (1002 as of this comment).

**Comment by cybik** [comment]
Circling back: this gets solved by https://github.com/yuzu-emu/yuzu/pull/8368/

However, the game is still unplayable.

**Comment by german77** [comment]
It doesn't get fixed?  what's the issue now?

**Comment by zhengwz** [comment]
The latest EA version (2737) is still unable to launch the game, it is always launching, the last version that can run is 2684. @german77 
![Screenshot](https://user-images.githubusercontent.com/20317922/170636647-566474b8-8447-4ec4-9b64-dee37a2568be.png)

**Comment by german77** [comment]
It's not in EA yet. But it should work on the #8368 PR artifact

**Comment by german77** [comment]
Setup of controllers is a bit funny. the game demands a specific configuration. player 1 - single right. player 2 - dual joycon. Don't forget to configure both players with the same joycons input and motion

**Comment by cybik** [comment]
I am on Linux. Here's what I tested.
(Legend: PX <Connect Controller>, <Input Device>)
* 1.2.0, P1/Right/Right, P2 Dual/Dual, Connected -> No Go, P2 disabled in Yuzu configuration after game start
* 1.2.0, P1/Right/Right, P2 Dual/Left, Connected -> No Go, P2 disabled in Yuzu configuration after game start
* 1.2.0, P1/Right/Right, P2 Left/Left, Connected -> No Go, P2 disabled in Yuzu configuration after game start (just for the kick)
* 1.2.0, P1/Right/Dual, P2 Dual/Dual, Connected -> No Go, P2 disabled in Yuzu configuration after game start
* 1.2.0, P1/Dual/Right, P2 Dual/Dual, Connected -> No Go, P2 disabled in Yuzu configuration after game start, game hard-reconfigures P1 to Right/Right even

There's something else forcing P2 to self-yeet itself here somehow. (I'm in the discord if there's anything I can do to track this down further)
