### ISSUE TITLE
Yuzu EA Appimage not run ROM

### ISSUE THREAD

**Issue by liberodark** [yuzu-emu/yuzu#8921]
Hi,

First thanks for this PR : https://github.com/yuzu-emu/yuzu/pull/6667
That would be great to leave chose for non using flatpak.
But have see one issue when you try to run game with appimage in cli that only lauch the GUI not the game.
But if you build yuzu you have no issue and if you using EA PineApple that work too.
If you have time to fixe this issue in Appimage version.

Best Regards

**Comment by Docteh** [comment]
#8871 is what caused it. 

`./usr/bin/$exec "$*"`
vs 
`exec ./usr/bin/yuzu "$@"`

well, `$*` vs `$@`

might be worth telling https://github.com/darealshinji/AppImageKit-checkrt about it? I gotta see if I can coax the checkrt part of it to work...

**Comment by liberodark** [comment]
Strangely out of appimage work but in appimage : 

```
Unhandled SIGSEGV at rip 0x00000000a14efe
Error of segmentation (core dumped)
```

**Comment by MrSco** [comment]
Any updates on this? I think everyone who is running EmuDeck and just updated in the last 5 days or so got the new appimage version that has this CLI game path bug… myself included. Thanks for all your hard work on this project. It’s awesome!

**Comment by MrSco** [comment]
> Strangely out of appimage work but in appimage :
> 
> ```
> Unhandled SIGSEGV at rip 0x00000000a14efe
> Segmentation error (core dumped)
> ```

the new 1176 version fixes the appimage launching for most games, but it still has this segmentation error for some games from command line, but same game will launch fine from gui

**Comment by Docteh** [comment]
You should file separate issue for that, so people can pipe in with the games that are exhibiting this, and maybe also test on systems.

**Comment by liberodark** [comment]
Have try EA 2970

```
Unhandled SIGSEGV at rip 0x00000000a1c50e
Segmentation error (core dumped)
```

**Comment by MrSco** [comment]
i tried EA 2970 and still get an error from command line trying to run this one game. the same game launches fine from gui in linux and also from gui And command line in windows. this is the only one of 10 games i've tested that has this issue.


`139)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
Unhandled SIGSEGV at rip 0x0055d2de291f0f
/tmp/.mount_yuzu.AaMBtS5/AppRun: line 18: 21103 Segmentation fault      (core dumped) $APPDIR/AppRun-patched "$@"
(139)(deck@steamdeck ~)$ "/home/deck/Emulation/tools/launchers/yuzu.sh" -f -g "'/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp'"
Qt Concurrent has caught an exception thrown from a worker thread.
This is not supported, exceptions thrown in worker threads must be
caught before control returns to Qt Concurrent.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/tmp/.mount_yuzu.AmkF2rP/AppRun: line 18: 21192 Aborted                 (core dumped) $APPDIR/AppRun-patched "$@"
(134)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
Qt Concurrent has caught an exception thrown from a worker thread.
This is not supported, exceptions thrown in worker threads must be
caught before control returns to Qt Concurrent.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/tmp/.mount_yuzu.AhJcZJp/AppRun: line 18: 21273 Aborted                 (core dumped) $APPDIR/AppRun-patched "$@"
`

**Comment by liberodark** [comment]
That not only steam deck issue in linux issue.
Have try on steam deck and on my computer.

**Comment by Titaniumtown** [comment]
I can reproduce this issue on the steam deck

**Comment by MrSco** [comment]
Not sure if this will help fix the issue, but I’ve found that when I update yuzu via EmuDeck smash bros launches from command line one time. And then fails for subsequent launches until yuzu is updated again

**Comment by liberodark** [comment]
Yes now that work better on steamdeck with EA 2975

**Comment by MrSco** [comment]
For me using EA 2975 still has the same issue... game launches fine on fresh yuzu install first time, but then after closing game/yuzu and relaunching, it throws segmentation error from command line (gui continues to work ok)...

`(1)(deck@steamdeck ~)$ "/home/deck/Emulation/tools/launchers/yuzu.sh" -f -g "'/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp'"
libpng warning: iCCP: known incorrect sRGB profile
(deck@steamdeck ~)$ "/home/deck/Emulation/tools/launchers/yuzu.sh" -f -g "'/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp'"
Unhandled SIGSEGV at rip 0x00557bb73ccf0f
/tmp/.mount_yuzu.Aa8cSF3/AppRun: line 18: 194340 Segmentation fault      (core dumped) $APPDIR/AppRun-patched "$@"
`

**Comment by Docteh** [comment]
@liberodark what if you try a full path with the AppImage? I filed https://github.com/yuzu-emu/AppImageKit-checkrt/pull/4 to make the current working directory get preserved but its not in yet.

**Comment by MrSco** [comment]
yea, i tried full path with AppImage instead of yuzu.sh, same outcome... Here's a symptom timeline...

Launch from command line:
`(1)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
Unhandled SIGSEGV at rip 0x00564366c6cf0f
/tmp/.mount_yuzu.Az5r1y1/AppRun: line 18: 204904 Segmentation fault      (core dumped) $APPDIR/AppRun-patched "$@"
`
Launch from gui: launches fine

Launch from command line again: 
`(139)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
Qt Concurrent has caught an exception thrown from a worker thread.
This is not supported, exceptions thrown in worker threads must be
caught before control returns to Qt Concurrent.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/tmp/.mount_yuzu.Ailz6EK/AppRun: line 18: 205190 Aborted                 (core dumped) $APPDIR/AppRun-patched "$@"
`
Launch from command line again (this time it tries to launch but stuck on yuzu loading screen):
`(134)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
libpng warning: iCCP: known incorrect sRGB profile
`
Launch from command line any subsequent time: 
`(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
Unhandled SIGSEGV at rip 0x005564938e5f0f
/tmp/.mount_yuzu.A2xLXMK/AppRun: line 18: 205407 Segmentation fault      (core dumped) $APPDIR/AppRun-patched "$@"
(139)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
Unhandled SIGSEGV at rip 0x007f0a3e68f515
/tmp/.mount_yuzu.AKxoBvr/AppRun: line 18: 205489 Segmentation fault      (core dumped) $APPDIR/AppRun-patched "$@"
`
and this is the only nsp that i have that does this. and the same nsp runs fine on windows from command line... gotta be apptimage/linux related.

**Comment by Docteh** [comment]
Huh, that Segfault should be fixed in https://github.com/yuzu-emu/yuzu/pull/8989 what version are you using?

**Comment by MrSco** [comment]
Maybe test on steam deck OS? I dunno. Happens with latest mainline and EA 2975

**Comment by liberodark** [comment]
@Docteh 
I think issue is fixed in Linux & SteamOS that work : 

With EA 2980

./yuzu-early-access.AppImage -f -g "/home/pc/Documents/Switch/My Game.xci"  (Work only with Fullpath)
Linux Desktop OK
SteamOS OK

**Comment by MrSco** [comment]
I'm still getting the same segmentation errors from commandline using latest EA build 2987 on the steam deck for the one game. gui launch works fine for all games.

**Comment by MrSco** [comment]
https://github.com/yuzu-emu/yuzu/issues/8921#issuecomment-1261414301

**Comment by liberodark** [comment]
Please try XCI game @MrSco

**Comment by MrSco** [comment]
![ksnip_20221003-212042](https://user-images.githubusercontent.com/11297411/193714199-e4870237-06c4-4a8e-a0c0-918dbb615fbd.png)

I get error when I try to use xci file from command line. filename makes no difference. launches fine from gui...

`(127)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/ssbu.xci"
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1158, resource id: 16785052, major code: 40 (TranslateCoords), minor code: 0
libpng warning: iCCP: known incorrect sRGB profile
[AVHWDeviceContext @ 0x7e847c6c8a00] Cannot load libcuda.so.1
[AVHWDeviceContext @ 0x7e847c6c8a00] Could not dynamically load CUDA
[AVHWDeviceContext @ 0x7e847c6c8f80] Failed to initialise VAAPI connection: -1 (unknown libva error).
Failed to open VDPAU backend libvdpau_radeonsi.so: cannot open shared object file: No such file or directory
[AVHWDeviceContext @ 0x7e847c6c9700] VDPAU device creation on X11 display :0 failed.
Unhandled SIGSEGV at rip 0x007f073cc6eae7
/tmp/.mount_yuzu-xcxXbXx/AppRun: line 18: 27249 Segmentation fault      (core dumped) $APPDIR/AppRun-patched "$@"
`

**Comment by liberodark** [comment]
@MrSco Please try this version : 
https://wormhole.app/zjWzY#jAjvb78AwVm1iL9vp9P11A
```37b790f59122e80534c65b6146ac8d6fc7f429ef6130ea984b6b991822261d09  yuzu-early-access.AppImage```

**Comment by MrSco** [comment]
That version seems to work better, but still crashes sometimes when launching from command line.
I did some tests. If the game launched successfully, I'd quit with deck's start+select hotkey and try again from command line...

First command line try (FAIL):
```
(126)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
Unhandled SIGSEGV at rip 0x00000000758dca
Segmentation fault (core dumped)
```

Second command line try (SUCCESS):
```
(139)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
libpng warning: iCCP: known incorrect sRGB profile
[AVHWDeviceContext @ 0x7f14146c7e80] Failed to initialise VAAPI connection: -1 (unknown libva error).
```

Third command line try (SUCCESS):
```
(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
libpng warning: iCCP: known incorrect sRGB profile
[AVHWDeviceContext @ 0x7ea0f06ca080] Failed to initialise VAAPI connection: -1 (unknown libva error).
tcache_thread_shutdown(): unaligned tcache chunk detected
Aborted (core dumped)
```

Fourth command line try (FAIL):
```
(134)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
Unhandled SIGSEGV at rip 0x007f8207b8f697
Segmentation fault (core dumped)
```

Fifth command line try (SUCCESS):
```
(139)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by liberodark** [comment]
Yep but this release is Official Yuzu EA 2989.
Thank you for your tests I think it proves that yuzu works well on steam deck but that maybe some improvements are to be expected.
Can you tell me which version you usually use?

**Comment by MrSco** [comment]
I wouldn’t say it works well. It works well with some games from command line and inconsistent and unpredictable with others. I use yuzu EA 2989 and steam os stable.

**Comment by liberodark** [comment]
The best thing to do is to submit all the worries here that you have but I have no problem launching my games under Linux or SteamOS on my side.

**Comment by liberodark** [comment]
@MrSco Just for test can you try this release : https://wormhole.app/19vOy#njV1hAwlT-kW4TQ_jSh2JQ

**Comment by MrSco** [comment]
```
/home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros. Ultimate [B+U1769472+99DLC].nsp"
./bin/yuzu: error while loading shared libraries: libavcodec.so.59: cannot open shared object file: No such file or directory

```

**Comment by MrSco** [comment]
still no fix for this the stable or ea releases?

**Comment by MrSco** [comment]
any updates? still happening. super smash won't launch from command line but mario kart (and other nsp) launches just fine everytime from command line. both launch fine from gui. using latest stable and latest EA, but have same issue.

`(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros Ultimate.nsp"
Unhandled SIGSEGV at rip 0x00007f0002f6cdd0
Killed
(137)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros Ultimate.nsp"
Qt Concurrent has caught an exception thrown from a worker thread.
This is not supported, exceptions thrown in worker threads must be
caught before control returns to Qt Concurrent.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Killed
(137)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros Ultimate.nsp"
Unhandled SIGSEGV at rip 0x000000000079150a
Killed
(137)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Super Smash Bros Ultimate.nsp"
Unhandled SIGSEGV at rip 0x00007f6f2676fffd
Killed
(137)(deck@steamdeck ~)$ /home/deck/Applications/yuzu.AppImage -f -g "/home/deck/Emulation/roms/switch/Mario Kart 8 Deluxe [B+U786432+1DLC].nsp"
libpng warning: iCCP: known incorrect sRGB profile
(deck@steamdeck ~)$ 
`

**Comment by omnomasaur** [comment]
Still having this issue in latest stable (1474).  I'm including 4 logs.  


[yuzu_log-cli_launch_failure.txt](https://github.com/yuzu-emu/yuzu/files/11811414/yuzu_log-cli_launch_failure.txt) is the log from a cli game launch that failed.  Notably there are a lot of assertion failures.  

[yuzu_log-cli_launch_success.txt](https://github.com/yuzu-emu/yuzu/files/11811456/yuzu_log-cli_launch_success.txt) is the log from a cli game launch that worked properly.  No assertion failures here.  

[yuzu_log-gui_lauch_success.txt](https://github.com/yuzu-emu/yuzu/files/11811458/yuzu_log-gui_lauch_success.txt) is from a gui launch.  Launching from the gui always works and never has assertion failures.  

[yuzu_log-cli_launch_success2.txt](https://github.com/yuzu-emu/yuzu/files/11811457/yuzu_log-cli_launch_success2.txt) is weird.  The game launched and played successfully here but there are still some assertion failures of the same variety.  

The only real recurring thing in the cli output is that "Unhandled SIGSEGV at rip 0x00000000007d7ac1"  always appears when crashing (go figure).

**Comment by bugrakaan** [comment]
> Still having this issue in latest stable (1474). I'm including 4 logs.
> 
> [yuzu_log-cli_launch_failure.txt](https://github.com/yuzu-emu/yuzu/files/11811414/yuzu_log-cli_launch_failure.txt) is the log from a cli game launch that failed. Notably there are a lot of assertion failures.
> 
> [yuzu_log-cli_launch_success.txt](https://github.com/yuzu-emu/yuzu/files/11811456/yuzu_log-cli_launch_success.txt) is the log from a cli game launch that worked properly. No assertion failures here.
> 
> [yuzu_log-gui_lauch_success.txt](https://github.com/yuzu-emu/yuzu/files/11811458/yuzu_log-gui_lauch_success.txt) is from a gui launch. Launching from the gui always works and never has assertion failures.
> 
> [yuzu_log-cli_launch_success2.txt](https://github.com/yuzu-emu/yuzu/files/11811457/yuzu_log-cli_launch_success2.txt) is weird. The game launched and played successfully here but there are still some assertion failures of the same variety.
> 
> The only real recurring thing in the cli output is that "Unhandled SIGSEGV at rip 0x00000000007d7ac1" always appears when crashing (go figure).

I was here to report exactly the same stuff. Somehow running yuzu from terminal via the AppImage causes very random crashes to happen. The only difference is the latest stable version is 1475 now and still this issue is still happening.

**Comment by rkfg** [comment]
Can anybody try to build the debug version and check in gdb where it crashes for you? I noticed that for me it segfaults at https://github.com/yuzu-emu/yuzu/blob/master/src/core/loader/nsp.cpp#L107 because `secondary_loader` is null at this point. But it doesn't always happen so I suspect there's a race condition somewhere. Sometimes the game starts just fine. I use `-f -g /absolute/path/to/game` (testing on `Luigi's Mansion 3`), built yuzu from master.

The cause of `secondary_loader` being null is this line: https://github.com/yuzu-emu/yuzu/blob/master/src/core/file_sys/submission_package.cpp#L153 when looking for `title_type` 0x80 (Application) and `type` 0x03 (Control). I just installed Yuzu for the first time a couple of days ago so I really don't know the internals, but putting debug `std::cout` output here and there helps to track it. Probably some entries for the game aren't always populated in time or at all which is what causes it. It's hard to tell if this error is the same as in the above reports because they don't include the debug info.

Try building yuzu and running it under gdb like this: `gdb -ex run --args bin/yuzu -f -g /path/to/game.nsp`

If you see something like this:
```gdb
Thread 1 "yuzu" received signal SIGSEGV, Segmentation fault.
Loader::AppLoader_NSP::Load (this=0x7fff18007b40, process=..., system=...) at /home/rkfg/soft/svn-soft/yuzu/src/core/loader/nsp.cpp:129
warning: Source file is more recent than executable.
129         const auto result = secondary_loader->Load(process, system);
(gdb) 
```
Then it's this bug (the line numbers are different because I added a lot of debug output).
