### ISSUE TITLE
Softlocks in Pokemon Sword/Shield

### ISSUE THREAD

**Issue by rgbarros120** [yuzu-emu/yuzu#9002]
Good afternoon. I've been playing pokemon sword for about ten minutes and the game just hits 0fps and crashes out of nowhere.

My Specs: RYZEN 5 1600; GTX 1650 OC 4GB; 16GB DE RAM (2400MHZ)
DRIVER: 517.48

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9676145/yuzu_log.txt)

**Comment by german77** [comment]
Can you try setting a network interface and see if still crashes

**Comment by rgbarros120** [comment]
> Can you try setting a network interface and see if still crashes

Even so it still crashes

**Comment by rgbarros120** [comment]
I think the problem is even in the ldns builds. In builds other than ldns the game does not crash.

**Comment by german77** [comment]
Are you on discord? I want you to test one build and see if works there or not

**Comment by rgbarros120** [comment]
> Are you on discord? I want you to test one build and see if works there or not

The game really has a softlock problem, I played about 30 minutes on the EA 2978 build, then the fps went to 0 and the emulator crashed once and for all.

**Comment by rgbarros120** [comment]
> > Are you on discord? I want you to test one build and see if works there or not
> 
> The game really has a softlock problem, I played about 30 minutes on the EA 2978 build, then the fps went to 0 and the emulator crashed once and for all.

![Sem título](https://user-images.githubusercontent.com/73244003/193357371-7ae082ac-4669-4f8a-92a4-890471f97246.png)

**Comment by german77** [comment]
I'm aware this issue really exist. You aren't the only one with issues. But we need to narrow down this issue, hence I want to try some custom builds with different things enabled to see what is the faulty component.

**Comment by rgbarros120** [comment]
> I'm aware this issue really exist. You aren't the only one with issues. But we need to narrow down this issue, hence I want to try some custom builds with different things enabled to see what is the faulty component.

It must be some feature of the ldn that they implemented that is causing a problem, it can only be because before not having ldn there was not this problem.

**Comment by Sylencer90** [comment]
My gf faces this issue a lot recently too. Some weeks ago the game would only crash once or twice every few days. Now she told me it crashes every 30-60mins and performance decreased too.

Regular non-patreon yuzu version here.

**Comment by rgbarros120** [comment]
> My gf faces this issue a lot recently too. Some weeks ago the game would only crash once or twice every few days. Now she told me it crashes every 30-60mins and performance decreased too.
> 
> Regular non-patreon yuzu version here.

So it is. That's exactly what's happening. You have to wait for the developers to fix this soon, which I think is kind of difficult, they don't pay much attention to this game.

**Comment by liberodark** [comment]
Yes have same issue on Yuzu EA sometimes is freeze.

**Comment by liberodark** [comment]
Crash with EA 3000 (On Steam Deck)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9729051/yuzu_log.txt)

**Comment by liberodark** [comment]
Sorry (for duplicate) have create dedicated issue about this. @german77 
Because I was wondering if this is only related to Pokémon. But I actually had the crash especially on pokemon.

**Comment by german77** [comment]
Seems like pokemon is a special case because it keeps insisting on using LDN. I need someone to test for solutions since I don't have this kind of crash. If you are up to the task ping me on discord

**Comment by liberodark** [comment]
No problem for Discord : liberodark#0928

**Comment by Sylencer90** [comment]
It stopped for a few versions, but now it's back since mainline 1204 or something.
But the general issue that is freezes upon **forced** saving & sometimes on catches, trees don't respawn and pokejobs can't be finished **unless you put in manual date by hand**.

I'm so sad this game don't get any more love from the devs :(

**Comment by LOuroboros** [comment]
> it freezes upon **forced** saving

Yup. This happened to me twice already while farming the Mining Duo's treasures. I also had freezes while catching a Pokémon some time ago, but I haven't gotten any as of lately.

On a separate note hopefully related to this issue, I noticed something veery strange.

If I have Yuzu's Network Interface set to "None", this "`Service.LDN <Error> core\hle\service\ldn\ldn.cpp:InitializeImpl:543: No network interface is set`" line gets printed in the log every once in a while. It's the only line with the `<Error>` prefix.

Thinking that perhaps something useful could be obtained out of messing with the network connection, I decided to try the game again after setting the Network Interface to my own Ethernet connection.

After a while of playing, I had the game freeze in the Battle Tower which was in line with my previous experiences when I had the Network Interface set to None *(i.e. the game freezing randomly after playing for a while)*, however, there's one very strange thing about this freeze; it's what was written in the log.

![sublime_text_20221029_223658253](https://user-images.githubusercontent.com/4485172/198858694-c22eb437-24ba-4b4a-8970-c481ea85be24.png)

This log plagued with these concerning-looking errors is HUGE. It's a 100MB file. I imagine it's because it was being updated right until I closed Yuzu understanding that the game was never gonna get back on track.

https://user-images.githubusercontent.com/4485172/198858853-9a6a4e1e-ed19-4515-bdfb-7770198f2979.mp4

Perhaps those "Unmapped Write 8/16/32/64" might be helpful somewhat? I don't know if they're related to the cause of the freezes, but they very well could.

Here's the full log compressed into a .zip folder using 7zip.

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/9894905/yuzu_log.zip)

**Comment by liberodark** [comment]
Crash from Yuzu EA 3066

**Log** 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9896901/yuzu_log.txt)

```
[ 181.542170] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:57: (STUBBED) called
[ 181.542390] Service.LDN <Info> core/hle/service/ldn/ldn.cpp:OpenAccessPoint:383: called
[ 181.542705] Service.LDN <Info> core/hle/service/ldn/ldn.cpp:CreateNetwork:397: called
[ 181.542786] Service <Info> core/hle/service/sockets/bsd.cpp:SocketImpl:477: New socket fd=0
[ 181.791082] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 181.791147] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[ 182.129217] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 182.129268] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[ 182.458195] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 182.458244] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[ 182.561158] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:505: 0xc85c619b4c6e0f99
[ 182.564078] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:505: 0x1972c8de1d03f969
[ 182.565917] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:505: 0x2826e0985f88a21f
[ 182.567755] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:505: 0x6934d2ccd5907c0e
[ 182.569870] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:505: 0x2febe62be5ef8a34
[ 182.791546] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 182.791600] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[ 183.126577] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 183.126630] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[ 183.457722] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 183.457772] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[ 183.792361] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 183.792427] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[ 184.127635] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 184.127695] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[ 184.460240] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 184.460286] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[ 184.645712] Service <Info> core/hle/service/sockets/bsd.cpp:CloseImpl:839: Close socket fd=0
[ 184.648300] Service.AM <Warning> core/hle/service/am/am.cpp:SetTerminateResult:1542: (STUBBED) called, result=0x0000EA01
[ 184.648574] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:709: Signalling debugger, PANIC! info1=0x00000010509B1E68, info2=0x0000000000000004
[ 184.648580] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:operator():691: debug_buffer_err_code=EA01
[ 184.648583] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:758: Emulated program broke execution! reason=0x0000000000000000, info1=0x00000010509B1E68, info2=0x0000000000000004
[ 184.648585] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:96: Backtrace, sp=00000010509B1CA0, pc=000000000BC96BA8
[ 184.648590] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:97: Module Name         Address             Original Address    Offset              Symbol
[ 184.648591] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:99: 
[ 184.803080] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 000000710037EBA8    000000000BC96BA8    000000000037EBA8    
[ 184.803097] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 00000071001801E8    000000000BA981E8    00000000001801E8    nn::diag::detail::Abort(nn::Result const*)
[ 184.803099] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 000000710017ED3C    000000000BA96D3C    000000000017ED3C    
[ 184.803100] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 000000710017EE08    000000000BA96E08    000000000017EE08    
[ 184.803102] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 000000710032F238    000000000BC47238    000000000032F238    
[ 184.803104] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 00000071003248F8    000000000BC3C8F8    00000000003248F8    nn::os::WaitEvent(nn::os::EventType*)
[ 184.803105] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: main                0000007101863C8C    0000000009867C8C    0000000001863C8C    
[ 184.803107] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: main                0000007101835C20    0000000009839C20    0000000001835C20    
[ 184.803109] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: main                000000710183668C    000000000983A68C    000000000183668C    
[ 184.803110] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 0000007100329E88    000000000BC41E88    0000000000329E88    
[ 184.803111] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: sdk                 000000710032E294    000000000BC46294    000000000032E294    
[ 184.803113] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:103: unknown             0000007100000000    0000000000000000    0000000000000000    
```

**Comment by Sylencer90** [comment]
Now I know why I stopped playing this game....the fcking freezes upon forced saving, especially on the Dynamax Adventures.
Impossible to complete more than 1 with all workarounds I found on the web.

Been like that since I played it last time and that was on yuzu mainline version 6xx or 7xx.

**Comment by BParks21** [comment]
I can confirm I get softlocks randomly.

**Comment by Sylencer90** [comment]
Issue still present. The other freeze upon forced saving, still an issue since mainline 6xx.
Bumping this to maybe get this fixed, otherwise the support for shield can be dropped since the 2nd DLC of the game can't be fully completed since it forces saving a lot.

**Comment by liamwhite** [comment]
Error EA01 fixed by #9474. Other issues unknown.

**Comment by Sylencer90** [comment]
> Error EA01 fixed by #9474. Other issues unknown.

Thank you. Sadly, the freezes upon forced saving hasn't been fixed with that :(.

**Comment by Scrooge200FES** [comment]
I'm still getting crashes on the game. I have default settings, but my Internet connection is set to Wi-Fi. I'm on Yuzu 1284 and always play on the latest version.

Today, I was able to play for 20 minutes before an abrupt freeze and crash. Here is my log:
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10306049/yuzu_log.txt.old.txt)

**Comment by BParks21** [comment]
Yeah still crashing pretty easily for me as well.

**Comment by Sylencer90** [comment]
Bumping this post. 

Please, for the love of god, can we get some attention for this game?
