### ISSUE TITLE
Slow load times and 3D images flickering in Animal Crossing: New Horizons

### ISSUE THREAD

**Issue by Odzinic** [yuzu-emu/yuzu#9130]
Hello,

After updating Yuzu to version 1191 I found that 3D images (such as the ones in the DIY crafting menu) started constantly flickering. Load times also increased and it seems like they get longer the longer the play session is (Around 30-40 seconds after about an hour of playtime). 

These issues was not present in version 1190 and reverting back to 1190 fixed them.

Some more posts with people having this issue:

https://www.reddit.com/r/yuzu/comments/y0gas5/animal_crossing_flickering_3d_model_when_creating/
https://www.reddit.com/r/yuzu/comments/vta1dp/animal_crossing_new_horizons_objects_flickering/

Please let me know if I can provide some logs or test something to help bisect the issue. Thanks!

**Comment by liamwhite** [comment]
Please update to yuzu 1207 or later as this should fix the AC:NH issues.

**Comment by Odzinic** [comment]
Thank you that fixed the issue. It seems that Emudeck may be behind on Yuzu versions so the issue persists there with the most "up to date" emulators.
