### ISSUE TITLE
yuzu crash after loading screen

### ISSUE THREAD

**Issue by morialo3** [yuzu-emu/yuzu#9597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

r22985.fda0e98

### Description of Issue

Tried to launch "Bayonetta 3", loading screen appears, and before the game's menu appears, it crashes and throw this error, from terminal:
```
❯yuzu                                                                                              
libpng warning: iCCP: known incorrect sRGB profile ## not an issue.
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/array:217: std::array::const_reference std::array<unsigned long, 4>::operator[](std::array::size_type) const [_Tp = unsigned long, _Nm = 4]: Assertion '__n < this->size()' failed.
zsh: IOT instruction  yuzu ## my shell complains.
```

### Expected Behavior

On previous builds, this game launches without crashing.

### Reproduction Steps

Use said build, launch from terminal, launch said game, Enjoy!

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10382594/yuzu_log.txt.old.txt)

### System Configuration

CPU:intel-10870H
GPU/Driver:nvidia-3080 MAX-q
RAM:32gig
OS:Manjaro-Linux

**Comment by G-Spawn** [comment]
the issue has been reported to devs afaik. hopefully they can address soon enough. sorry for the inconvenience.

**Comment by liamwhite** [comment]
Fixed in mainline 1303

**Comment by heavysink** [comment]
Hi, the error still presents at EA 3512 and mainline 1404. Switching to OpenGL does not solve the issue so I think it is not relevant to the vulkan...

**Comment by liamwhite** [comment]
I am able to launch Bayonetta 3 just fine using the mainline 1404 AppImage.
