### ISSUE TITLE
Insanely high GPU usage since mainline 1298

### ISSUE THREAD

**Issue by duke912** [yuzu-emu/yuzu#9624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1298 and over

### Description of Issue

When playing Mario odyssey (and any other game), gpu usage goes from 25 - 30% to over 70% under the same circunstances (resolution, etc), making the gpu run hotter and getting no additional performance. Verified with msi afterburner

### Expected Behavior

Lower gpu usage to pre mainline 1298 level

### Reproduction Steps

Just playing any game is enough

### Log File

....

### System Configuration

CPU: i7 6700k
GPU/Driver: rtx 3070, latest driver
RAM:16gb
OS: Windows 10

**Comment by liamwhite** [comment]
fixed by #9589 (mainline 1302 and later)

**Comment by duke912** [comment]
> fixed by #9589 (mainline 1302 and later)

Gpu usage still over 70% even on 1307. So, it's not fixed, but whatever

**Comment by liamwhite** [comment]
Disable the setting then.
